### ISSUE TITLE
Node Download Page is DOWN

### ISSUE THREAD

**Issue by isaacfi** [nodejs/nodejs.org#1064]
I've tried to download Node JS for Windows x64 from: 

https://nodejs.org/dist/v6.9.2/node-v6.9.2-x64.msi

But the server responds 502.

Regards.

* **URL**:
* **Browser version**:
* **Operating system**:

**Comment by xogeny** [comment]
I'm having issues with `node-gyp` builds because it wants to download https://nodejs.org/download/release/v6.9.2/node-v6.9.2-headers.tar.gz which currently throws a `522` status code for me, *e.g.*,

```
$ wget https://nodejs.org/download/release/v6.9.2/node-v6.9.2-headers.tar.gz
--2016-12-09 11:20:55--  https://nodejs.org/download/release/v6.9.2/node-v6.9.2-headers.tar.gz
Resolving nodejs.org... 104.20.23.46, 104.20.22.46, 2400:cb00:2048:1::6814:172e, ...
Connecting to nodejs.org|104.20.23.46|:443... connected.
HTTP request sent, awaiting response... 522 Origin Connection Time-out
2016-12-09 11:21:26 ERROR 522: Origin Connection Time-out.
```

If you visit that link in a browser, you get a note from CloudFlare indicating the error is originating at `nodejs.org`.

**Comment by MylesBorins** [comment]
This is a dupe of https://github.com/nodejs/nodejs.org/issues/1061

We are aware of the issue and hoping to have a solution in the very near future. Thanks for your patience

You can find more details on https://github.com/nodejs/build/issues/562
