### ISSUE TITLE
Misleading download option: official node docker image

### ISSUE THREAD

**Issue by psrodka-neurosys** [nodejs/nodejs.org#1070]
* **https://nodejs.org/en/download/**:
* **Chrome 54**:
* **Windows 10 Pro**:

On the website https://nodejs.org/en/download/ one can find official node docker image which is misleading as it is Linux based image and since we got now Linux and Windows images one can be confused by the label. 

Proposition
1. Create Windows based image, e.g.:

 \# escape = ` (backtick)
 FROM microsoft/windowsservercore
 SHELL ["powershell", "-command"]
 \# Required by chocolatey
 ENV chocolateyUseWindowsCompression false
 \# Download and run chocolatey installer
 RUN iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
 \# install 7 zip as required by nodejs installer
 RUN cinst -y 7zip.install
 \# Install nodejs
 RUN cinst -y nodejs.install

2. Update download site to reflect complex reality ;)

**Comment by fhemberger** [comment]
@nodejs/docker Do you want to add a Windows tag to the official Docker image? I'm not so sure if its feasible, the `windowsservercore` base image is already whopping 5 GB. Not the best foundation to run Node.js microservices. ;)

@psrodka-neurosys Regarding your example: Instead of using chocolatey, you should grab the Windows ZIP file directly from our dist, e.g.: https://nodejs.org/dist/latest/node-v7.4.0-win-x86.zip - Thus you always have the latest releases and don't need additional tools for installation. Powershell 5 has the function `Expand-Archive $pathToZip $targetDir`, that should work as well.

**Comment by psrodka-neurosys** [comment]
@fhemberger Thanks for comment. If you get from .../latest/`version` you will need to know the `version` number, so you will have to update Dockerfile along with new version of Node. In my example you are only using `cinst -y nodejs.install`, which I assume is latest on chocolatey. Maybe Node.js can introduce  https://nodejs.org/dist/latest/node-latest-win-x86.zip - that would be most effective.

About 5GB - that is true, but if Windows guys are using Node as frontend layer for ASP.NET MVC application, then they will benefit anyway from Node on Docker as images don't sum up - they will share the same base image `windowsservercore`.

The real reason is still the confusing link name - there is no more Docker, period. Since introducing containers to Windows we will have to distinguish between the two not compatible worlds.

**Comment by fhemberger** [comment]
@psrodka-neurosys `/latest/` was just an example. You always want a *specific* version which is tagged accordingly to ensure reproducible builds. Same goes for the base image.

And the link name is just fine. Host system and image base system don't matter in the container world. We went with the most widely adopted base systems (Debian and Alpine Linux) for our image. Both options work totally fine on Docker for Windows as well.
