### ISSUE TITLE
Ubuntu Bash environment on Windows 10

### ISSUE THREAD

**Issue by ColinMoulds** [nodejs/nodejs.org#1253]
Windows 10’s Fall Creators Update, Arriving September 2017

Microsoft is making it easier to set up Ubuntu for Windows 10 by bringing Ubuntu to the Windows Store. This is the same Ubuntu Bash environment you can install on current versions of Windows 10, but easier to install.

Fedora and openSUSE are also coming to the Store, so it’s easier to set up different Linux environments.

This may or may not cause issues with installation of node. Just thought i would bring it up just in case.

**Comment by gibfahn** [comment]
Thanks for the heads up. FYI this is the issue tracker for the website, you probably wanted to raise this on https://github.com/nodejs/node.

The Windows Subsystem for Linux is not currently supported by Node (possibly just because no-one has done the work to get machines set up and added to our test infra). We still get (and try to fix) bug reports for it though, so it's good to know that it's going more mainstream.

**Comment by ColinMoulds** [comment]
Alright, Thanks for the heads up.

I have now opened the issue on there as it may be more useful

(New to Github)
