### ISSUE TITLE
doc: Small grammar error

### ISSUE THREAD

**Issue by remixie** [nodejs/nodejs.org#1259]
https://nodejs.org/en/about/
Google Chrome 59.0.3071.86 (Official Build) (64-bit)
Windows 7 Enterprise

In the third sentence, there should be a comma after "done" and before "Node". That is all.

**Comment by gibfahn** [comment]
>Upon each connection the callback is fired, but if there is no work to be done Node is sleeping.

I'm not sure this sentence does need a comma.

**Comment by javacoolme** [comment]
How about an insertion of a " because " or " - "

**Comment by tniessen** [comment]
I am not a native English speaker myself, but I think I would intuitively put a comma there:

> ... but if there is no work to be done, Node is sleeping.

**Edit:**

[grammarbook.com](http://www.grammarbook.com/punctuation/commas.asp) seems to confirm this:

> When starting a sentence with a dependent clause, use a comma after it.

**Comment by gibfahn** [comment]
I don't think `because` is correct here.

On further checking I think you're right, if ..., then ... sentences should always have a comma (e.g. [link](https://www.grammarly.com/blog/conditional-sentences/).

I think the `is sleeping` is a bit weird too, maybe:

`, Node will sleep` or `, Node sleeps`
