### ISSUE TITLE
Arm v6 missing

### ISSUE THREAD

**Issue by rcomeau** [nodejs/nodejs.org#1270]
* **URL**:
* **Browser version**:
* **Operating system**:

**Comment by rcomeau** [comment]
no download page for Arm v6 Current

**Comment by jasnell** [comment]
ping @rvagg ... when you get a chance, can you promote the 8.1.2 armv6 artifacts :-)

**Comment by rcomeau** [comment]
npm compiled 8.1.2 for my pi_ 0w, but it took almost 24 hours!!

**Comment by krydos** [comment]
Just wonder if we have anything where we can build for armv6?

I tried to search on `nodejs/build` and didn't find anything. Do we build semi-manually for armv6? I mean is there  no automatic job for this? :(

**Comment by gibfahn** [comment]
>Just wonder if we have anything where we can build for armv6?

The release ci instance is hidden, and unfortunately the config scripts aren't kept in source control.

You can look at the test ci though, which does have [an arm6 build job](https://ci.nodejs.org/job/node-cross-compile/label=cc-armv6/).

What exactly were you looking for?

**Comment by krydos** [comment]
@gibfahn thank you for the answer.

Sorry, I just though `nodejs/build` is somehow connected with release ci instance, I just tried to search for `armv6` and didn't find anything.

**Comment by gibfahn** [comment]
So the build definitely completed, and the tarballs are there. I think the problem is that the builds took ages, so the other releases were promoted before the arm6 builds were ready (the job took 2hr15).

@nodejs/build @nodejs/release the job is here, https://ci-release.nodejs.org/job/iojs+release/1765/nodes=pi1-raspbian-wheezy/ can someone promote the builds? According to [`releases.md`](https://github.com/nodejs/node/blob/master/doc/releases.md#2-nodejsorg-access) you need access to the dist user on nodejs.org.

**Comment by jorisvervuurt** [comment]
Looks like the armv7 build is now available on the Downloads page, but the armv6 build still results in a 404. 😔

**Comment by rvagg** [comment]
oh whoops! sorry. unfortunately only the releaser can promote extra binaries. That's done now, https://github.com/nodejs/nodejs.org/pull/1272
