### ISSUE TITLE
Wikimedia logo marked for deletion because of licencing issue

### ISSUE THREAD

**Issue by silverwind** [nodejs/nodejs.org#1345]
See https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:Node.js_logo.svg

Apparently the SVG logo approximation I made based on the AI file was marked for deletion because the linked source page (https://nodejs.org/en/about/resources/) does not make that logo available under a free licence.

I'm not sure how to proceed. Shall we add the SVG logo to that page and note it as freely available as opposed to the official AI version?

**Comment by Fishrock123** [comment]
Hmmm, not really sure either. :/

**Comment by hackygolucky** [comment]
I will bring this up in our internal team meeting. This feels silly. More like a relic of the group who originally worked on the files vs. what's actually allowed.

**Comment by hackygolucky** [comment]
@silverwind When you say _free license_, are there restrictions on what licenses can be used for content on Wikimedia? The logo is allowed to be used for noncommercial use, as indicated in the [policy](https://nodejs.org/static/documents/trademark-policy.pdf)

> 2. Links to the Node.js Foundation
You may use Node.js or the Node.js logo on your website as a hyperlink to the home page of the Node.js
Foundation. Please make sure any use of the marks follow the Visual Identity Guidelines. For example,
the marks may be resized, but not modified in any other way. And remember that you must avoid any use
that implies any endorsement of you or your site or otherwise by the Foundation. The Foundation may in
the future define specific image files to use for these use cases.

Maybe I'm misunderstanding the problem.

**Comment by refack** [comment]
The request was made by an anonymous user, that's a red flag. I'm referencing the policy in a reply to that request.

**Comment by refack** [comment]
I opened a deletion request for an old duplicate that might have been scraped by a bot 3 years ago.
https://commons.wikimedia.org/wiki/File:Node.js_logo_2015.svg
The references in that pages show it's not used in any wiki entry.

**Comment by fhemberger** [comment]
Deletion debate on Wikimedia is flagged as closed, closing this issue as well.
