### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [nodejs/nodejs.org#1373]
Hello 

Could you please reorginize documentation for nodejs?

I am new programmer to nodejs and for me it is very hard to understand what resources I need to read for learning nodejs from start to end. Of course I can search with google and find some "hello world" applications, but first of all they do not provide all features, the second - most of them may be outdated and use old nodejs pattern, features or API. 

The documentation Url (https://nodejs.org/en/docs/) points to:

1. API which lists features in alphabetical order so it is hard to understant what can be read first, what is the core nodejs features and what are minors
2. List of guides. But for new developer it is unclear do they describe all nodejs feature or not?

Could you please consider spring documentation as example? Spring has it Spring Core module and they created documentation (https://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/) which has:

1. both html (sigle and per header variants) and pdf version. Pdf version is very good for offline reading from mobile phone. Yes phone is not a device for developing, but it is very suitable for reading everywhere when you a couple of minutes.
2. They split all documentation into numeric sections and it is very usefull because you can easy see what you have read and what is not, you can easy the order in which you should read the documentation. You can start from the bening and be ensure that when you read end you read whole documentation. (which is impossible when documentation is split into alphabetical list)

So in total the best way is to do reorganization to have API docs and numered guide. But as "quick fix" could please create a page where there is a numeric list which describes the order for guide and API reading?

* https://nodejs.org/en/docs/
* Chrome 60.0.3112.113
* windows 10 version 1703

**Comment by mlosh** [comment]
SGTM

**Comment by fhemberger** [comment]
Node.js and Spring are **very** different things, so comparing their style of documentation doesn't really fit.

Node.js is not a framework but a runtime, allowing you to execute arbitrary JavaScript code from the command line. It offers the same language set given in modern browsers (minus the DOM part for actually rendering websites). Additionally, it provides some basic low level API for file access, network (http, https, tcp, udp, etc.) and so on. There is also no stdlib like in other programming languages, all higher level tools, functions, frameworks, etc. are composed of [npm packages](https://npmjs.com), written by the community. The Node.js core tries to stay as minimal and compact as possible.

That makes it unfeasible to write "hello world" applications "providing all features" as you suggested, because it highly depends on what you want to do. Want to work with files? Look at the file system API (`fs`). Need a simple web server? The `http` API is your friend. Need a bit more abstraction? Choose one of the various excellent Node.js web-frameworks provided by the community (like express, hapi, restify). So there's no "reading order", as all those APIs are single building blocks to enhance your vanilla JavaScript code with additional features.

However, we provide a set of guides for various topics that might help you getting familiar with certain technical aspects of Node.js: https://nodejs.org/en/docs/guides/
