### ISSUE TITLE
Windows installer for 64-bit installs 32-bit version of node 4.0?

### ISSUE THREAD

**Issue by koteisaev** [nodejs/nodejs.org#150]
Hello!
Just tried to download the Nodejs 4.0 installer using different urls, including
https://nodejs.org/dist/latest/node-v4.0.0-x64.msi
https://nodejs.org/dist/v4.0.0/node-v4.0.0-x64.msi

The installer offers the following instalation path for node:
C:\Program Files (x86)\nodejs\
This path is for 32-bit apps.. 
Does this means that this installer deploys 32-bit version of nodejs? 
Win version - Windows 10 Pro 64 bit (build 10240

**Comment by rvagg** [comment]
thanks @konstardiy, this is actually an issue for nodejs/node rather than this repo, but I'll pull in some folk on this here anyway / @nodejs/platform-windows: would you mind having a look at this please? It's a bit of a concern although I seem to recall it installing in the right location when I was trying it out.

**Comment by koteisaev** [comment]
@rvagg Thanks for fast reply. I was a bit shocked with that. Initially tried to install a hapi package abd seen that it expects _strange_ version of node (4.0.0) and after short googling I was hm... smashed into fundamental changes nodejs is going through and i was totally unaware of.
Tryed to run installer (msiexec) as administrator and it did not helped.

**Comment by piscisaureus** [comment]
@konstardiy Did you try to upgrade from a 32-bit version of node? I've noticed the behavior you're seeing in the past - but only when the user already had a 32-bit version installed. This happens because windows installer carries over the settings used for the previous installation, including the installation directory.

**Comment by orangemocha** [comment]
What @piscisaureus said. @joaocgreis fixed this, but the fix only applies to fresh installs. @konstardiy can you try to uninstall first and then run the 4.0 installer?

**Comment by seishun** [comment]
As a user of Windows 10 64-bit I can confirm that it defaults to Program Files for me.

**Comment by koteisaev** [comment]
Thanks for hint about uninstalling the old version of Node, it helped.
This hint can be a part of FAQ..
