### ISSUE TITLE
https://nodejs.org/docs/  

### ISSUE THREAD

**Issue by AM-77** [nodejs/nodejs.org#1841]
* **URL**: https://nodejs.org/docs/
* **Browser version**: chromium 69
* **Operating system**: LinuxMint

https://nodejs.org"/en"/docs/ 
https://nodejs.org"/en"/download/  

when remove the "/en" it shows the indexof page with all of the server content instead of the 404 page.

**Comment by WaleedAshraf** [comment]
Or it should redirect to some default English version.

**Comment by refack** [comment]
> when remove the "/en" it shows the indexof page with all of the server content instead of the 404 page.

https://nodejs.org/docs/ is the repository of all released API docs by version, its not an indexof. Similarly https://nodejs.org/download/.
It's a feature, maybe not intuitive, but intentional. (and makes it so we don't have a prefered language...)

P.S. we even link to it (almost) from the README https://github.com/nodejs/node#download
