### ISSUE TITLE
Cannot download node on windows

### ISSUE THREAD

**Issue by sitthykun** [nodejs/nodejs.org#188]
I cannot download Node on windows platform 
 https://nodejs.org/dist/latest/node-v4.1.0-x64.msi

**Comment by rvagg** [comment]
you caught a tiny window where we just released v4.1.1 and v4.1.0 was still "latest", try again at nodejs.org and you'll get an accurate link

@nodejs/website I'm thinking that instead of using "latest" we should use the version number, this isn't the first issue reported with this problem, there's a few minutes delay (at least) between the switch of "latest" and a website rebuild.

**Comment by sitthykun** [comment]
I see it. Great job.

**Comment by fhemberger** [comment]
@rvagg I just fixed the link on the home page.
