### ISSUE TITLE
Add domain node.js.org

### ISSUE THREAD

**Issue by marvinschopf** [nodejs/nodejs.org#2253]
It would be very cool if you'd get the domain "node.js.org" as an alias for nodejs.org.
You can get the domain here: [js.org](js.org).

**Comment by fhemberger** [comment]
This setup is limited to GitHub pages. Setting up a separate GitHub page and create a manual meta redirect to nodejs.org in an HTML file (only those are supported by GitHub) seems to be too much of a hassle. The redirecting will also have a performance impact on page load times.

Nice idea in general, but because of the implementation -1 on that from my side.

**Comment by Trott** [comment]
I don't think there's anything stopping someone else from setting up such a redirect, FWIW.

**Comment by Trott** [comment]
> I don't think there's anything stopping someone else from setting up such a redirect, FWIW.

Update: I'm doing this right now to prevent someone else from doing it and redirecting to evilsite.example.com. Obviously, I'll happily hand it over to the nodejs GitHub org if it's decided that is where it should live. Plus the js.org repo wiki indicates that nodejs can just take it from me anyway.

**Comment by Trott** [comment]
OK, I've set this up and submitted a PR at https://github.com/js-org/js.org/pull/3115. 

You can go to https://trott.github.io/node.js.org/ to experience the redirect. It will only redirect the home page, so this is a low-value (but also low-overhead) redirect. I'm mostly doing this to prevent someone from grabbing the domain and using it to serve insulting/malicious/otherwise-bad material.

**Comment by MattIPv4** [comment]
> I don't think there's anything stopping someone else from setting up such a redirect, FWIW.

Myself or Indus, who is the founder of the project, manually review all requests for domain, requiring all sites to have a valid reason for requesting the subdomain name and ensuring the requested target site has valid content, so it would never end up at evil content. I would think it unlikely that I'd let this domain out to any other project than something directly node related due to the popularity of node, but I totally understand why you're requesting a redirect for node.js.org. I'll follow this up further in the js.org PR. :)

**Comment by marvinschopf** [comment]
Wow, I didn't expect that you would to that so fast! Amazing. :)

**Comment by MattIPv4** [comment]
@Trott / @fhemberger what are your thoughts on bringing https://github.com/Trott/node.js.org into the nodejs org so that from the perspective of js.org, we know the page is controlled by the organisation and not just one individual which poses potential risks, though I imagine Trott is plenty trustworthy.

cc @indus

**Comment by fhemberger** [comment]
@MattIPv4 Sure, I'm fine with that.

**Comment by Trott** [comment]
> @Trott / @fhemberger what are your thoughts on bringing https://github.com/Trott/node.js.org into the nodejs org so that from the perspective of js.org, we know the page is controlled by the organisation and not just one individual which poses potential risks, though I imagine Trott is plenty trustworthy.
> 
> cc @indus

In progress: https://github.com/nodejs/admin/issues/370

Won't be done for another 3 days, but I don't expect any opposition on it.

**Comment by Trott** [comment]
All done. Thanks, everyone.
