### ISSUE TITLE
htmllint issues on Windows

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2459]
It seems httmllint gets confused by the missing space in the handlebar templates, but this issue only appears on Windows hence why Travis CI builds just pass.

```
C:\Users\xmr\Desktop\nodejs.org>npm t

> nodejs.org@ test C:\Users\xmr\Desktop\nodejs.org
> npm run test:lint && npm run test:unit && npm run test:smoke


> nodejs.org@ test:lint C:\Users\xmr\Desktop\nodejs.org
> standard --fix && htmllint **/*.hbs && stylint layouts/css && markdownlint "**/*.md" -i "node_modules/"

layouts/partials/footer.hbs: line 3, col 20, value must match the format: dash
layouts/partials/footer.hbs: line 3, col 1, tag is not closed
layouts/partials/header.hbs: line 10, col 9, tag is not closed
layouts/partials/navigation.hbs: line 6, col 11, tag is not closed
```

I don't think we should change the code to add the space back. In fact I'm not sure if htmllint offers any value... The website was full of serious HTML validation errors that were caught by the official HTML validator which I plan to add here eventually.

Let me know how to proceed.

**Comment by XhmikosR** [comment]
https://travis-ci.org/XhmikosR/nodejs.org/jobs/576205825

If Windows on Travis CI wasn't so slow, I'd say we added it, but it's too slow.

Are there any plans to switch to GitHub Actions CI?

**Comment by ghost** [comment]
@XhmikosR , It seems this is also checked in CI, just like what you said in https://travis-ci.org/XhmikosR/nodejs.org/jobs/576205825, and I've fixed it in my submit ;)
![image](https://user-images.githubusercontent.com/52018749/64055294-2ebeed00-cbbe-11e9-87f8-dc1f01f6f129.png)

BTW: Do you mean the time in windows or Linux is a huge difference when using Htmllint? I'd say that we should keep it because a pretty code needs time to be checked with. As for GitHub Action CI, this may be done in the future. Until now we have to use Htmllint instead.

**Comment by XhmikosR** [comment]
@MaledongGit: yeah I meant Windows, but Travis is a no go for this currently, unfortunately.

About your PR, I commented there. These aren't real issues, and for example, it hasn't warned us for indentation issues. We shouldn't be using htmllint IMO.

**Comment by ghost** [comment]
@XhmikosR：You mean in Linux it skipped the check……？This is really strange....

**Comment by XhmikosR** [comment]
I'd say it's a bug in htmllint probably, that behaves differently on Windows hence the errors.

**Comment by XhmikosR** [comment]
Closing since this no longer occurs.
