### ISSUE TITLE
Help needed with staled process of translation

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/nodejs.org#2488]
I've already discussed and planned a lot of stuff related to translation, but in case of @zeke is very busy the process is staled.

https://github.com/nodejs/i18n/issues/72

Could someone help me with credential to Crowdin of nodejs?

**Comment by zeke** [comment]
Hey @alexandrtovmach. Sorry I haven't been able to unblock you on this, and thanks for being kind and patient even though this must be very frustrating. I have access to the credentials, but we use GPG to secure them, and I'm currently unable to install the `dotgpg` tool we use to extract them. It's a ruby dependency and every time I try to install it get that dreaded `extconf.rb` compilation error.

I am also pretty swamped with other work, and that's why I've not taken the time to delve into solving that problem. @obensource is the only other person I know of who administers this. Maybe we can find some other folks to help unblock this?

cc @nodejs/i18n

**Comment by obensource** [comment]
@zeke & @alexandrtovmach just left a comment in the issue. Very sorry for the delay – swamped at work and personal things too. I have the credentials and just safely shared them with Zeke. Let me know how you'd like to proceed and I'll do my best to help you get some momentum going with nodejs/i18n#72.

**Comment by Trott** [comment]
(Should this issue be closed now that things are moving again in the i18n repo?)
