### ISSUE TITLE
Use the same JS linting as the node repo

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2523]
Adapted for the frontend JS files since ES5 is used there.

**Comment by XhmikosR** [comment]
I'd like to take a stab at it, but I'm not sure where to start. Also, this change will probably be a big one, from a quick look. But at least this way we'll be consistent. And then we can look into #2524, which IMO is super important.

**Comment by carterbancroft** [comment]
I'm interested in giving this a shot as well, even if it's just a piece of the overarching issue but first I'd like to clarify what I'm getting myself into. Since I'm so new to the node repos can anyone help me suss out what specifically needs to be done.

My most basic question is, does all the linting from the node repo need to be front end adapted and implemented over here? It seems like there are a lot of custom rules (https://github.com/nodejs/node/tree/master/tools/eslint-rules) in addition to what's defined in `.eslintrc.js`.

Maybe a good start would be to implement what's in https://github.com/nodejs/node/blob/master/.eslintrc.js minus the custom rules?

Thanks for bearing with all my ignorance!

**Comment by nschonni** [comment]
My 2 cents would be to see if you can create a repo like https://github.com/nodejs/remark-preset-lint-node based on the config. Then that config could be used by Node-core plus other repos

**Comment by carterbancroft** [comment]
Thanks, I appreciate the 2 cents. I wondered if a new shared repo would be appropriate here. Lemme see what I can figure out.

**Comment by ovflowd** [comment]
Closing as all PRs got merged already and this is probably not relevant anymore. Feel free to reopen if needed.
