### ISSUE TITLE
`build:deploy` fails with `EMFILE: too many open files`

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/nodejs.org#2654]
I'm opening this for ideas about solving the `EMFILE: too many open files` errors that happen when running the full build on CI.

It seems the OS on CI has a maximum limit of 4096 open files which we pass. I tried using graceful-fs, but the error still happens.

* Initial patch to demonstrate the issue: https://github.com/nodejs/nodejs.org/runs/253355870.
* With graceful-fs: https://github.com/nodejs/nodejs.org/runs/253360046

We'll need to run the full build at some point when we have linkinator run for all locales.

**Comment by XhmikosR** [comment]
Perhaps we should use [async queue](https://caolan.github.io/async/v3/docs.html#queue)?

Any help welcome. If we go with the async queue solution #2633 will become obsolete I think.

**Comment by Trott** [comment]
@nodejs/website

**Comment by phillipj** [comment]
You were thinking about using an async queue to not build *all* the locales at one, right? If so that sounds like a good idea 👍

It would ofcourse make the build take a bit longer, but I don't see that as an issue in practise. Sounds much more important and valuable to be able to verify a full build succeeds in CI, than be concerned about the time it takes.

**Comment by XhmikosR** [comment]
Any help welcome. We need to see how much slower it'll be also.
