### ISSUE TITLE
Inconsistent install instructions for Linus distros

### ISSUE THREAD

**Issue by medikoo** [nodejs/nodejs.org#278]
In some places of [installation documentation](https://nodejs.org/en/download/package-manager/), there is suggestion to install `node` and `npm` separately (e.g. for [arch linux](https://nodejs.org/en/download/package-manager/#arch-linux)) which results in npm being installed in other version than one bundled together with node.

That produces inconsistent setup among people that rely on that documentation. I think it would be more correct if instruction would ensure that npm comes at version at which it was bundled with installed node version.

Yesterday in my team we struggled for a while with a bug, which was purely caused by unexpected npm version being used, while all that developer followed when setting up Node.js for his environment was linked instruction document.

**Comment by fhemberger** [comment]
@rvagg You might want to update this in the nodesource docs as well (where this text was taken from).

**Comment by fhemberger** [comment]
@nodejs/build Can someone please have a look at the Linux install instructions? Separate `npm` hay or nay?

**Comment by rvagg** [comment]
It's inconsistent because it actually is inconsistent across packagers. Many distros dictate that you can't install these things in a single bundle--one of the reasons that we bundle them together in the [NodeSource Linux distributions](https://github.com/nodesource/distributions) is because we think these rules are (mostly) stupid.

If Arch comes with an `npm` package and a `nodejs` package which includes `npm` as well (whyyyyyy????) then I suggest that you (1) contact the people responsible for this mess in Arch and suggest they fix it cause it's stupid and (2) open a pull request here to change the instructions to be accurate. I don't use Arch so I don't feel qualified to suggest a way forward here.

I'm pretty sure the instructions are correct for Fedora and EL because they have these same rules. But in those cases I'd just recommend you get your packages from a [better source](https://github.com/nodesource/distributions) anyway, but that's listed on the doc already.
