### ISSUE TITLE
[doc] package.json doc link broken

### ISSUE THREAD

**Issue by sciamp** [nodejs/nodejs.org#2907]
I'm opening another issue about broken links since every issue I can find is already closed.

Inside the getting started about `package.json` file the link to the online doc is broken.

**steps to reproduce**
1. browse to https://nodejs.org/en/knowledge/getting-started/npm/what-is-the-file-package-json/
2. scroll to bottom to this
![image](https://user-images.githubusercontent.com/234184/72905789-5d865d00-3d31-11ea-9ce3-de63d88a6724.png)
3. click the `online docs` link [0]
4. hit the github 404 page

Thanks :)

[0] https://github.com/npm/npm/blob/master/doc/files/package.json.md

**Comment by Trott** [comment]
Correct link is https://docs.npmjs.com/files/package.json if someone wants to submit a pull request.

**Comment by Trott** [comment]
As so often I do with pages in our mostly-unmaintained knowledge base, I find myself compelled to suggest removing this page entirely. The part about Node.js only being aware of the `name` and `version` fields. With ES Modules, that's no longer true. [I don't think it was true even before that. `main` surely was used by the `node` binary, no?] There could be other things too. Rather than have to update this and similar documents, I'd prefer we link to a relatively stable external resource (or omit it entirely if we have no reason to have the knowledge base at all--I'm not sure how many people use it and how useful it is).

**Comment by Trott** [comment]
The page is also written as if `npm` is the only package manager (because at the time it was written, it basically was), and while it is certainly the biggest and most well-known, and likely to stay that way for the foreseeable future, beginners trying to get started with a `yarn` project may be flummoxed.

**Comment by XhmikosR** [comment]
Just remember to redirect any removed pages. I'm all for removing obsolete content, I just don't like finding 404 pages :)

**Comment by liquidbyte** [comment]
I am facing an issue in the page below,

https://nodejs.org/en/knowledge/getting-started/what-is-require/

"it is considered an absolute path. NOTE: you can omit ".js" and require will automatically append it if needed. For more detailed information, [see the official docs](https://nodejs.org/docs/v0.4.2/api/modules.htmll#all_Together...)"

For the below link,

https://nodejs.org/docs/v0.4.2/api/modules.htmll#all_Together...

Should I open a new bug?

**Comment by XhmikosR** [comment]
@liquidbyte that will be fixed in #2914 which I accidentally came across this link https://github.com/nodejs/nodejs.org/pull/2914#pullrequestreview-364189300

**Comment by XhmikosR** [comment]
I'll fix this but I also see another issue: the `title` taken from the frontmatter key is not being passed through Markdown. I'll see if this can be fixed while at it.
