### ISSUE TITLE
Support multiple documentation version sets

### ISSUE THREAD

**Issue by shelleyp** [nodejs/nodejs.org#305]
You're supporting two Node versions at a time. 

But you're only providing one set of documents--for the version of Node that's going away in April. 

If you're going to support two versions of Node, you have to provide access to the API documentation for both versions.

**Comment by fhemberger** [comment]
If you look at https://nodejs.org/en/docs/, we are providing API docs for [0.10.x](https://nodejs.org/docs/latest-v0.12.x/api/), [0.12.x](https://nodejs.org/docs/latest-v0.10.x/api/), the [current version](https://nodejs.org/api/) and in fact to all Node.js versions back to 0.1: https://nodejs.org/docs/.

**Comment by fhemberger** [comment]
@rvagg Can we have a 'latest-lts' symlink for API docs as well?

**Comment by shelleyp** [comment]
If you're going to support two versions of Node at the same time, you need to provide access to both APIs at the top most level of the web site, at the same time. If you're going to have two downloads for Node on your download page, you really need to have two APIs at the top most API page.

**Comment by phillipj** [comment]
Maybe we should have two API links in the aside on the docs page aswell? E.g:
![skjermbilde 2015-10-30 kl 14 17 13](https://cloud.githubusercontent.com/assets/1231635/10846610/3ebb85cc-7f11-11e5-95a5-9d277b47bedf.png)

**Comment by shelleyp** [comment]
No, not closed. 

This page needs to list both. https://nodejs.org/api/

**Comment by shelleyp** [comment]
Agree with @phillipj suggestion.

**Comment by mikeal** [comment]
Updated the title to be more productive.

**Comment by mikeal** [comment]
I'm not convinced that https://nodejs.org/api/ needs to have both. That link has always been to the latest current docs, since literally forever :)

Totally agree that the docs page needs to link to both.

Have we considered also linking to the API docs in the download page for each release and in the automated release post of each release?

**Comment by mikeal** [comment]
Reopening as I don't see the comment that closed this with links to new issues :(

**Comment by dominykas** [comment]
I very much disagree that "this has been this way forever" is an argument to keep things as is. In fact, it's an argument for the opposite - this was a _problem_ forever, esp. during the months when I couldn't upgrade, say, 0.8 to 0.10 (which reminds me I need to update my bookmark which currently points to 0.12...)

You have to consider the use cases. Most likely, I'm looking for the docs that I need to complete my work _this instant_. So a link to docs next to the download link is kind of useless - if my task is "find the docs for module X for version Y", am I expected to google "download version Y"? Not saying the link shouldn't be there - just that it's not enough.

The version switch needs to present and findable. Not sure how prominent it should be, but it does need to be in the header (e.g. a version dropdown next to "Index | View on single page | View as JSON" - just not sure if that's easily doable for historic releases - it could be solved via external JS with knowledge about versions or smth). I know I've seen some APIs do this... just can't find an example of the top off my head...

Also if by some sorry chance you're looking at an oooooold version of the docs, then a prominent warning a la "Hey, are you sure you don't want to go try the new stuff that young folks are using?" might be in order. I know I've seen some APIs do this too...

(does reopening this mean #307 can be closed?)

**Comment by mikeal** [comment]
Leave both open for now because we need more than just #307 and we can use this as a meta-issue for tracking all related issues.

**Comment by mikeal** [comment]
@dominykas IMO, the only reason we support "/api" is for backwards compatibility with old links. There's a lot of issues with it, the most important one being that it doesn't support localization of the api documentation. Whenever possible we're trying to move to pages within the new website to represent these resources so that they can be saner and localized.

If anything, I think that /api should be turned into a forward to either the latest LTS or Stable docs. That way at least the url is version specific.

**Comment by dominykas** [comment]
Oh. Right. Localization - that also needs to be a switch present on the page... 

I'm not sure a redirect would be a good idea for ~~SEO~~ _users_ coming from search engines. An English doc with an LTS (or latest Stable) at a permalink URL is a _good_ idea. In general, a redirect is treated as a "don't lead people to this page" thing by search engines, which means that the SERPs would list results for some specific version, rather than a link to The Docs (this also depends on redirect type and `<link rel="canonical"/>`).

The "specific version" could be anything - but most likely, over time, it would become the most popular, most active version and a new release would not necessarily bubble up fast enough, since people would be bookmarking, sharing, i.e. passing link juice to the specific version and not The Docs and not to the current LTS/Stable. Having something at, say, `/de_DE/api` or `https://de.nodejs.org/api` would also make sense. Are there already any issues open on URL planning? (sorry, didn't have time for research just yet)

The switches in the docs pages can also have some sort of "my default" user preference, which allows you to set your preferred language and version. This would involve some trickery via the URLs when you need to see a non-default version, but it could serve all the goals - having clean URLs, having sane defaults, keeping old URLs working, but most importantly - allowing easy access to _the_ version of the docs one actually needs to complete the job at hand and go home to their families and friends.

**Comment by shelleyp** [comment]
But you don't have a "current" anymore. You have a LTS release and a stable release, and they're both "current". And you're encouraging people to pick LTS for larger more complex corporate apps, and stable primarily for smaller, more flexible apps. Hence, one could say that "current" should be the LTS version, than. 

So you can't forward /api to just one or the other. You'll need to create an API page with links to both.

**Comment by shelleyp** [comment]
I've added #309 for /api

**Comment by mrcrgl** [comment]
Hey, I already have the need to switch to older versions of nodes doc and, if not already opened, I would open that ticket. 

Since many companies are working with node 0.x, developers will get wrong informations in a web search. I also worked with django some time and they know about that problem and included a prior version switch to their documentation pages. I would recommend this solution. 

I would spend some time in solving it if you guys agree. 

Cheers

**Comment by dominykas** [comment]
Screenshot of how Django does it (fixed position, bottom, right; expands on hover):

![screen shot 2015-10-30 at 19 24 26](https://cloud.githubusercontent.com/assets/505619/10852896/f984bc96-7f3b-11e5-84bc-495059f62bc7.png)

They do have the version in the URL via redirect from root.

**Comment by shelleyp** [comment]
I like Django's approach, but expanding on hover is "hidden necessary content". A person may not know they need to hover over the 1.8 documentation number to discover links to the other versions. 

We don't need to be fancy. A new page at /api can list links to documentation for all supported versions (which would also include 0.x, since a version is still supported). It could also link to the folder with previous, no longer supported versions. 

The /docs page can have the sidebar modified, as discussed in another thread. And the front page can link the docs page to each install version that's displayed, as well as a link to the doc page. 

New versions won't be so common that maintaining this would be a burden. 

Unfortunately, this doesn't take care of issue about direct search engine results, drilling into the current API docs, because you can't link a "current" -- you have two currents.

**Comment by shelleyp** [comment]
I checked out Ubuntu, since it has a release system comparable to Node's. You click on Server Documentation, it goes to this page 

https://help.ubuntu.com/

To me, that's an effective page. As for the API drilldown - perhaps re-directs from all sub-folders back to this documentation page. I know it's ugly, but over time, the sub-folders will get connected to their version specific page. Bite the bullet, pay the cost now, for a system that can work into the future. 

Ubuntu also has specific directories labeled stable and LTS. That could work for us. By default, these would be the current stable and current LTS API documentation pages.

**Comment by mrcrgl** [comment]
The fixed overlay was added after djangos redesign. Before they had a select field, which also worked pretty fine. 

I would love to navigate from deep pages to different versions +1

**Comment by dominykas** [comment]
@shelleyp, I only listed what Django do, I didn't suggest node does the same :) Hover does have other issues (touch, etc), but it _can_ work by giving proper affordances through visual design. I'm just trying to collect examples of what other people have done to solve this problem. Also I'm not saying node shouldn't have all the other things you mention - multiple paths to the same content is a _good_ thing.

It also doesn't have to be hover at all - it may as well be direct links a la "Version: **LTS** | Stable | Other" - takes up pretty much the same space, but allows direct interaction for the most common (I'm guessing...) switch for LTS <-> Stable. Mind you, the terminology of LTS vs Stable for a newcomer is still unclear, so it may work better as "Version: 4.2.1 LTS | 5.0.1 | Older". There's plenty of good options, but deep page interlinking is a must.

It might be worth to have a separate issue for "Version switch on every page of the docs"?

**Comment by dominykas** [comment]
Squid has "latest" at the permalink (but also available via versioned URL). Each directive has a version switch at the top:

![screen shot 2015-10-30 at 22 40 52](https://cloud.githubusercontent.com/assets/505619/10857570/86a78606-7f57-11e5-9478-3040012b821b.png)

There's an index page listing all the versions for various directives:

![screen shot 2015-10-30 at 22 42 16](https://cloud.githubusercontent.com/assets/505619/10857575/8a9db190-7f57-11e5-8e7c-841f27757855.png)

**Comment by shelleyp** [comment]
@dominykas Good examples. 

If it's feasible to add a link to difference versions on each of the API's subtopics, it could be good. There's still the issue, though, of what is current? Because though v5 is the latest, it's not the LTS, and it isn't the only current release--only the current stable release. 

Have added three issues already on documentation. Hesitant to add another.

**Comment by dominykas** [comment]
My personal opinion "current" is LTS, but hey - that's just me. Since both v4 and v5 came out in such a quick succession it should be possible to make an "npm downloads" based vote in a month or so. If there's an easy switch - it matters a lot less anyways. Also it should be easy to A/B by randomly selecting whether LTS or Stable is "current" and seeing if people switch.

Mongo DB stores "latest" at permalink, allows switching on the sidebar via expandable options to another version:
![screen shot 2015-10-30 at 23 08 02](https://cloud.githubusercontent.com/assets/505619/10858097/1a4e006c-7f5b-11e5-83d1-f850a4838c12.png)

**Comment by shelleyp** [comment]
@dominykas if we end  up with one "current", I agree with you: it should be LTS. 

But, and I hate to sound like a parrot repeating the same thing, we do have two "current" releases: stable and LTS. MongoDB is a single current release. The version 3.0 is considered to be a replacement to 2.6 which is a replacement to 2.6 and so on. Drupal is the same way: though the org currently supports one older version (6.x), one release (7.x), and one in-development beta (8.x), there is only one official "current" release at a time. There's a sense of progression between the versions. 

Node.js is different, it's following the Ubuntu release model: there are two current releases at a time, stable and LTS. There's no real sense of progression: people are encouraged to pick one or the other, but you're not going to plan to progress from v4 to v5, because the real progression is more likely to be v4 to v6, and possibly v5 to v6, or v5 to v7. Maybe even v4 to v7. But never v4 to v5--never LTS to stable. 

At least, that's my understanding. 

Now your dropdown could work for this. The v5 could be listed as stable, v4 as LTS. My concern here is people may not understand what LTS and assume the stable release is the long-term release. 

Going to be tricky. An interesting challenge.

**Comment by dominykas** [comment]
Well, at the end of the day, you can only display one[1] thing at a particular URL, so a choice _will_ have to be made and that's regardless of the actual final URL layout (redirect or default content at the canonical URL). Node has two "current" release tracks - that's the reality, I'm not sure we should discuss pros/cons of the release cycle here?

I already touched on the fact that the naming (LTS vs Stable) might not be 100% intuitive (it can be simplified by not highlighting "Stable" and only adding LTS label where appropriate), but I'm not sure this is the appropriate thread to discuss that particular issue either, because more importantly, we need to look at the reader's context - does the LTS vs Stable distinction even matter to them at that particular moment? Why and how did they get to one of the docs [sub]pages? What are they trying to achieve?

Just some scenarios (please add more!):
- someone looking for a specific answer to a specific problem on their current version
- someone trying to figure things out and they don't even know which version they're using
- someone doing some investigation/research/picking up general knowledge
- someone following a link from stackoverflow for more details
- someone planning a migration to vX+1 [2]

One thing in common across all of these is that the reader is never looking for multiple versions of the docs (unless they're a power user, who actually uses multiple nodes, but I'm pretty sure they can figure out what to do even if there's no cross-linking on the site at all, i.e. like now). So, the reader is always looking for one version: it's either their version, or any version, or the Bestest version.

As long as the website guesses the "any" and "bestest" versions correctly (or they're set up politically to promote freshness or LTSness), and as long as there's an obvious and easy way to switch - it'll all be grand.

[1] I mean, sure, in theory you _could_ display two versions side-by-side in the same window, but lets not go there.
[2] In some projects I will totally move from LTS to Stable to LTS to Stable, since I don't need LTS there and as a module author I will do my best support multiple versions

**Comment by shelleyp** [comment]
We're not really discussing pros/cons of the release cycle as much as we're discussing the _realities_ of the release cycle. True, in some ways this issue could be considered a test case of the Node production paradigm, but there is no separate Github issue list for it. So, we'll have to make do.

When it comes to documentation it is imperative to the reader that they know which version they're reading. We all can agree on this. 

But I think we need to come to an agreement that the reader may not always want the same documentation set, each time they visit the site. 

If they're supporting a production version of an application that's created in one version of Node, at the same time they're developing a new version of the application in another version of Node, they may need to go back and forth between the documentation sets. So I think we need to come to an agreement that we shouldn't try to "hack" the reader's mind and "guess" what she or he wants, and dump them into one documentation set or another. 

There shouldn't be any issues with documentation on the front page or in the /docs page. The front page documentation can be listed under each release that's available on that page. In the /docs page, there is already a decent mock up of what to use in the sidebar, and the web folks can adjust the main page contents accordingly. Each set of API documentation linked in /docs should go to a version-specific directory, not a generic one.

Where we have a problem is /api. At this point there are three options I can see. 

Option 1 is to eliminate the generic /api, redirect all generic /api requests back to /docs, and from this time forward, list documentation under its specific release. It's not an especially attraction option, but it is an effective option. 

Option 2 is to make a decision that the current LTS is "current", in that it has the longest support cycle and is in the primary path for most application adoption. And adjust all the /api references accordingly, as long as they are annotated with version information. 

Option 3 is a variation of this, but for Stable. I dislike this one, though, because to all intents and purposes, Stable really isn't much more than a production-ready beta for the next LTS release. To all intents and purposes. 

A variation of Option 2 and 3 is to provide the toolbar/menubar at the top of each topic page in the API that provides quick and easy links to other versions of the documentation. It could be limited to supported versions only. 

So, if I arrive via search engine at Buffer and it's the LTS documentation version, a menu bar at the top (sidebar, floating bar, whatever the UI folks like) provides access to the 0.x documentation and the v5 documentation. 

With this approach, the /api can still exist, search engines will be happy, and the reader should only have to hit an extra link if they arrive at the wrong version of the documentation when they've made a search.

**Comment by dominykas** [comment]
@shelleyp, would it be correct to summarise that the core difference between the options 1 and 2/3 is that in the first case the reader is forced to make a decision on which version they would like to read [at the default /api URL] and in the second case the decision is made for them? In which case, I would have to disagree with "we shouldn't try to "hack" the reader's mind and "guess" what she or he wants" and I'd like to argue that "smart defaults" is one of the good UI practices, because it reduces the number of decisions the users have to make.

Think: "all people should make a choice between version A and version B" vs "some [how many?] people, who use version B, will have to switch away from version A".

> But I think we need to come to an agreement that the reader may not always want the same documentation set, each time they visit the site.

I absolutely agree that some users will need this, but I feel this is not the use case that the site should optimize for. This is a "power user" use case. Power users will know what to do - the site just needs to make it a little easier to achieve.

Either way - the switch needs to be there and as for /api - there is a little bit of politics here, alright, meaning that it matters whether the ummm community feels that it's important to emphasize that there are two release tracks or not.

My personal opinion is that this emphasis is unnecessary. I feel that it's best to communicate that "hey, node is awesome, pick the LTS and you won't be wrong", as it once again reduces the number of decisions (= learning curve = slower rate of adoption) people have to make and in this spirit, the /api should point to the LTS.

This is nice (despite that it has a completely different purpose):
![screen shot 2015-10-31 at 17 59 13](https://cloud.githubusercontent.com/assets/505619/10864530/25387018-7ff9-11e5-8a4f-aa334840315d.png)

In node's case, in a similar list, LTS and Stable in a similar list can be emphasized (with a color, e.g. green) or the old versions can be de-emphasized (by fading/greying out). LTS can have an even stronger emphasis, by making it bigger and bolder, i.e. visual hierarchy can solve a lot of problems.

How did this become such a long debate?...

**Comment by mikeal** [comment]
We actually had a long discussion about this at the collaborator summit. The consensus seemed to be:
- In the short term, implement a "django style dropdown" for switching between versions.
- Long term we should try to move to a single API doc which, on a per API basis, states the version that a feature was introduced and any compatibility issues and differences with prior versions of node.

Switching between versions in order to manually diff is a pretty horrible experience when you're trying to resolve discrepancies between versions. However, with our current content set it's better than nothing.

**Comment by shelleyp** [comment]
That sounds cool, @mikeal  

But what's going to change now? I'm assuming the /docs page will get the adjustments to account for documentation for both the current Stable and current LTS versions. Same for front page. Those should be simple fixes. 

But what will happen with /api? Which "current" version will it become? Both @dominykas and I believe it should be LTS, since it's the truly stable, production ready version that most people will probably use for their apps. But you currently have it as v5, which is gone in Spring, 2016.

**Comment by rvagg** [comment]
We now have the following in both https://nodejs.org/download/release/ (aka https://nodejs.org/dist/) and https://nodejs.org/docs/:
- latest -> v5.0.0
- latest-argon -> v4.2.1
- latest-v0.10.x -> v0.10.40
- latest-v0.12.x -> v0.12.7
- latest-v4.x -> v4.2.1
- latest-v5.x -> v5.0.0

These symlinks gets updated with each release of any line so they should always be correct. There was a bug that prevented the v4.x and v5.x symlinks from being created (they were working on iojs.org which run by the same code) but that's fixed now. The 4 -> 'argon' link is embedded in the code so when we have a new LTS name for v6 it'll have to be manually added.

I'm -1 on a `latest-lts` because we'll have overlapping lts releases soon, people should be explicitly using the correct url for the version they are using and we have no real way of knowing what version they (or the bulk of the user base) are on! This is similar to the reasoning behind removing any automatic semver-major upgrades for the [linux distributions](https://github.com/nodesource/distributions), you have to opt-in to a major version line and you'll only get upgrades on that until you explicitly change to a new line.

**Comment by rvagg** [comment]
code for this tooling is [here](https://github.com/nodejs/build/tree/master/setup/www/tools/latest-linker) if anyone wants to propose something different

**Comment by shelleyp** [comment]
I may not have been clear in my last comment. 

You're equating current with version number, but versions have been redefined with the release paradigm, in that there is no natural sequence of progression in Node versions now. 

Both v4 and v5 are "current". One is LTS, one is Stable. 

Since Stable is really primarily a pre-cursor for v6, it makes more sense to have the "current" /api doc link to the LTS version. We should assume that most professional use of Node will most likely be LTS, since it's guaranteed to be around longer and supported longer than Stable, which bites the dust in 8 short months.
