### ISSUE TITLE
doc: Error in the "How to log in Node.js" docs - custom logging solution

### ISSUE THREAD

**Issue by bttger** [nodejs/nodejs.org#3101]
Regarding the custom logging solution: https://nodejs.org/en/knowledge/intermediate/how-to-log/#custom-logging

The comparison of the `level` and the `debugLevel` is not working like that, because it must be `>=` instead of `<=`. Otherwise if you set the `debugLevel` to something lower than "error" it won't show the error logs. Also I would not recommend declaring a new variable with every call of the logging function. The `levels` should be exported as a property for the logger. My recommendation would be:
```javascript
var logger = exports;

logger.levels = ["debug", "info", "warn", "error"];
logger.debugLevel = "warn";

logger.log = function (level, message) {
    if (logger.levels.indexOf(level) >= logger.levels.indexOf(logger.debugLevel)) {
        if (typeof message !== "string") {
            message = JSON.stringify(message);
        };
        console.log(level + ": " + message);
    }
}
```

And if you want to work with multiple arguments through the rest parameter:
```javascript
logger.log = function (level, ...message) {
    if (logger.levels.indexOf(level) >= logger.levels.indexOf(logger.debugLevel)) {
        console.log(level + ":\t" + message.reduce((prev, curr) => {
            return prev + " " + (typeof curr !== "string" ? JSON.stringify(curr) : curr)
        }, ""));
    }
}
```

**Comment by Trott** [comment]
Hi, @bttger! Thanks for the issue.

The knowledge base articles were originally written something like 9 years ago and have not been much maintained since then. In my opinion, we should decommission the whole thing and maybe refer people to nodejs.dev instead.

That said, if you want to improve this one, please do open a pull request against https://github.com/nodejs/nodejs.org/blob/master/locale/en/knowledge/intermediate/how-to-log.md.

From a somewhat larger perspective, Node.js should probably implement a way to set the log level somewhere and then respect that setting in `console.debug()`, `console.info()`, `console.warn()`, and `console.error()`. Then people wouldn't need to write their own loggers that way.

**Comment by Trott** [comment]
Looking more closely, I think this article can and should be removed entirely. There are no doubt better treatments of the topic elsewhere and we don't need to include "how to attain log levels" in the knowledge base. And I'm not sure that the official site should be promoting `winston` (which is great) over `loglevel`, `pino`, etc.
