### ISSUE TITLE
I would like to suggest change the way of supporting #BlackLivesMatter

### ISSUE THREAD

**Issue by 0x00000FF** [nodejs/nodejs.org#3250]
First of all, Let me clarify that there's no intention for racial discrimination or being against the BLM movement.

I little bit surprised when I enter the nodejs.org because I couldn't find any download links for Node.js. Of course, I know you people doing it for the right thing with good will, human rights must be respected.

However, nodejs.org is basically for providing information about Node.js, so its content should be the first for the visitors. There supposed to be many way to support BLM and pay tribute for Mr. Floyd and deceased people, Instead of wiping main page out and putting brief links for the main contents on the bottom of the page.

In my opinion, putting dark banner on the top of the layout or attractive position is much better idea(and link to memorial page), so it can not to confuse developers like me, also support the movement.

Social movement is meaningful as is. but we should know that its achievement can be established on the cooperation, not in stubborn way. Thank you.

P.S. sorry for my bad english, if there were some words that can offend someone, please let me know more polite one.

**Comment by MylesBorins** [comment]
@0x00000FF the intent was for the full page replacement to be there for a week. There is a PR open already to replace the full page replacement with a banner that we plan to land Monday.

I understand that it is frustrating and inconvenient to not be able to quickly have access to the landing page. This was the point of the statement we made. While many projects included a banner we thought that replacing the entire landing page made a much bolder statement and would inspire more self education and discussion. Talking about race and racial injustice is an uncomfortable thing.

I'm going to close this issue because I think your request has been answered, but I'm happy to continue to discuss this. For what it is worth there are members of the node.js team who feel similarly to you, that a banner would have been a better approach. I still strongly believe we did the right thing, the statement was supposed to make finding things a bit more difficult and to force people to take a moment to reflect on lives lost and what we want to do about it.
