### ISSUE TITLE
website download area down

### ISSUE THREAD

**Issue by jmartiuk5** [nodejs/nodejs.org#336]
I cant access the download area it seems the site is down.

**Comment by bnb** [comment]
[Here](https://nodejs.org/en/download/)? Up for me. We need a bit more detail from you to actually know what's wrong.

**Comment by phillipj** [comment]
Re-open with more details if there's still an issue reaching our download page @jmartiuk5, closing this for now.

**Comment by rvagg** [comment]
@nodejs/build I think this might be a DigitalOcean backup thing, it happens around this time each week and the OP was a week ago. Remember that we pass-through for download tarballs so CloudFlare doesn't keep it up when the server is having trouble serving requests. The backup is COW but I wouldn't be surprised if all the writing to the log files fill up the available buffer space or something like that because the backups take a long time.

I'm hesitant to just disable backups without having a more solid backup solution for this server. We have most of it in Ansible but there is state on there that would be nice to keep, particularly logs, but there's likely lots of other things that would be nice to node lose in the case of catastrophic failure.
