### ISSUE TITLE
LTS downloads link

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/nodejs.org#373]
It would be great if we could link to https://nodejs.org/en/download/lts in case we ever decide to change which release line is the default.

In addition, how difficult would it be to make individual versions have the rich download display?

If necessary I may be willing to make these changes, but my time is.... limited.

**Comment by phillipj** [comment]
This could be broken up in three different changes:
1. create the download/lts page by copying `./locale/*/download/index.md` -> `./locale/*/download/lts.md`
2. change our own links from https://nodejs.org/en/download ->  https://nodejs.org/en/download/lts
3. add a redirect in nginx from https://nodejs.org/en/download ->  https://nodejs.org/en/download/lts for google and friends + visitor's bookmarks

By copying instead of moving in step 1, we dont have to synchronize the website release with adding the nginx redirect in step 3.

Would you agree or did I miss something @Fishrock123?

**Comment by fhemberger** [comment]
We could use the (unused) download page to explain lts/stable in detail, etc.

**Comment by fhemberger** [comment]
@Fishrock123 Is this ticket still relevant or can we close it?

**Comment by Fishrock123** [comment]
Still relevant. Ideally I'd be able to link to these rendered-pages per version.

That is pretty complex though. It means doing some ngnix hackery. I'll try to work on it soon.

**Comment by fhemberger** [comment]
@Fishrock123 Should we proceed with @phillipj's idea to prepare a separate LTS download page? Or do you prefer a different approach? Otherwise I'd like to close this issue, as there hasn't been any progress for 19 months.

**Comment by Trott** [comment]
@nodejs/website-redesign Is this a feature that will be in the redesigned website? If so, I'd be inclined to close this as it's been inactive for so long. But if it's not yet determined if it will be in the redesigned website, I don't want to close it....

**Comment by ovflowd** [comment]
@Trott yup this is already on the new website, so we can close this issue.
