### ISSUE TITLE
Why the BLM donation link was removed?

### ISSUE THREAD

**Issue by Shreyamkmr** [nodejs/nodejs.org#3928]
I used to see the BLM donation link on the website but now it has been removed. Any specific reason why?

**Comment by nschonni** [comment]
Looks like it was toggled off in https://github.com/nodejs/nodejs.org/commit/a87f468982dde3e5931f4c3a2ee7c67cc6253e67

**Comment by symmetric-dynamite** [comment]
Perhaps because the BLM movement self identifies as "radically Marxist", and the founder of the movement has been accused of corruption, gross negligence, and theft by other subsidiary chapters? Politics has no place in open-source programming. If you want to support the BLM movement, then go to their website and donate. Thai people, and most of the world, doesn't care about your Marxist views, and/or crazy left wing group-identity politics. We don't want to see it on open source platforms.

**Comment by ovflowd** [comment]
Closing as there no actions to be done here.
