### ISSUE TITLE
Potential "Edit on GitHub" improvements

### ISSUE THREAD

**Issue by Trott** [nodejs/nodejs.org#4000]
Saw this as a footer on MDN docs and thought it might be worth emulating.

![image](https://user-images.githubusercontent.com/718899/126713721-6a9ebec1-748b-4aad-a592-6eaf3c280720.png)

**Comment by ghost** [comment]
@Trott: Just for a quick modification, I've splitted the footer into two splits in verticle, is it right? Any suggestions for the formation?

![捕获](https://user-images.githubusercontent.com/52018749/129343079-c0417017-0a8e-47a3-b025-528d1816f701.JPG)

**Comment by Trott** [comment]
Looks good to me. 

I hate to say it because it was a great effort to make it happen, but I wonder if we want to get rid of the "Thanks you" box. It was a nice idea (I think it was my suggestion even), but no one sees it where it is, and we need to really start thinking about the website serving the user, which that box really doesn't do.

**Comment by Trott** [comment]
@MaledongGit Thanks for working on this!

**Comment by MaledongGit** [comment]
@Trott: 

I tend to keep this users' contributions, but two things confusing me:

1. Should we put it directly in the index page as a random mode? Or just remove it at "Contribution" page by nesting the dynamic image?

([![contributors](https://badges.implements.io/api/contributors?org=nodejs&repo=node&width=1280&size=48&padding=6&type=jpeg)](https://github.com/nodejs/node/graphs/contributors)

2. Since readme.md and contribution.md are both about "How to contribute to the Nodejs.org", so I don't think it related to node.....Is it suitable to show contributors for node instead of nodejs.org?

**Comment by ghost** [comment]
@Trott: I'll submit a PR affter removing the contributors, however I'll open another Issue to have a discussion on it.
