### ISSUE TITLE
feat: Is is necessary to add "Contributors" as a random mode in "Index" of nodejs.org?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#4043]
Ref: https://github.com/nodejs/nodejs.org/issues/4000#issuecomment-898749950

IMO: I tend to keep it, but not in the index page as a random mode. Just as many other GitHub's projects do——to make a dynamic contributors' wall in the "Contributors" page with a link:

[![contributors](https://badges.implements.io/api/contributors?org=nodejs&repo=node&width=1280&size=48&padding=6&type=jpeg)](https://github.com/nodejs/node/graphs/contributors)

**Comment by XhmikosR** [comment]
@Trott I see your point because it's in the footer. Let me know if you want me to drop it properly in one patch so that we can bring it up later if needed.

For what is worth, I don't mind having it, and I actually believe it's nice to have, but I get that it being in the footer might not be worth it.

PS. yeah, it was your request to add it in the first place 😛

**Comment by XhmikosR** [comment]
The contributors feature is gone now.
