### ISSUE TITLE
Formatting mistake at "What is the arguments object?" page

### ISSUE THREAD

**Issue by floreapaun** [nodejs/nodejs.org#4384]
```
myfunc
  .apply(obj, arguments)
  // concat arguments onto the
  .Array.prototype.concat.apply([1, 2, 3], arguments);
```
I think this should be written as:  
```
myfunc.apply(obj, arguments);

// concat arguments onto the
Array.prototype.concat.apply([1, 2, 3], arguments);
```
I don't know what is the meaning of that period on the concat function.

**Comment by Trott** [comment]
That page is also out of date. It says `arguments` is available inside all functions, which was true when it was written, but is no longer true because arrow functions are now a thing. There are likely other issues with it. In my opinion, we should remove the page. If we link to it anywhere inside text, we should update those links to point to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments.

In general, I'm not a fan of the knowledge base/guides on the web page. They may have once served a purpose but they now are mostly a liability and are neglected. The information they seek to provide is done much better elsewhere (such as, in this case at least, MDN).
