### ISSUE TITLE
es6 per version

### ISSUE THREAD

**Issue by sebakerckhof** [nodejs/nodejs.org#488]
This page specifies what features of es6 are available: https://nodejs.org/en/docs/es6/

However, it's not clear to me to which version this applies (LTS or latest) and if it's the latest how I can find what's available in an older version. It would be good if this page was versioned per node version.

**Comment by benjamingr** [comment]
Thanks for the report!

Some features explicitly have a footnote saying: "[2]: Only available in Node.js >= 5.x.x"

Everything else is available in the LTS release. That is - it's documented, but only for the two current versions (LTS and Latest stable).

How do you think we can clarify that page so users get a clearer idea of what's available where?

**Comment by strawbrary** [comment]
Yeah I agree, as new versions are released with new features it will become harder to tell which features are available since which version. Perhaps we could either add a column next to each feature to say "Available Since" with the version number, or organize it like a changelog and list the features that were added in each version?

**Comment by stevemao** [comment]
#434 is the PR that resolve this issue.

**Comment by williamkapke** [comment]
Perhaps http://node.green will help you?

**Comment by sebakerckhof** [comment]
@williamkapke thanks, very good reference site.

**Comment by stevemao** [comment]
Closing because of #671
