### ISSUE TITLE
release date for Node.js v0.9.3 is comically wrong year.

### ISSUE THREAD

**Issue by aberant** [nodejs/nodejs.org#489]
I now know why node.js is so fast! Time machines!

Actually it just looks to be a bit of a typo.  Node.js v0.9.3 is listed as having a release date of 2015-10-14 but was actually released in 2012

**Comment by rvagg** [comment]
Good catch, thanks for reporting @aberant, it looks like a few have slipped through as 2015: https://nodejs.org/download/release/index.tab

The cause was poor date sorting @ https://github.com/nodejs/build/commit/73d1682f429e61fbbb759c3bd3fbbd3ae826e96b combined with newer SHASUM256.txt files that have been put into some of these older directories, so they have a new modified timestamp on them.
