### ISSUE TITLE
Please, add the karakalpak language to your website

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#5015]
### Enter your issue on localizations here:

Hi, I'm from the Republic of Karakalpakstan. We are using Karakalpak language. Could you add our language to your website?

You can add it as a custom language on crowdin. Here is the information about the language:

Language name: Karakalpak

The dialect of: Not chosen
Crowdin code: kaa
Three letters code: kaa
Locale code: kaa
Text direction: left to right
Plural form: one, other

If you don't want to add it as a custom language, can we take the files locally and translate?

Thanks!

**Comment by ovflowd** [comment]
Hey, @alizhumagaliev, sadly, we cannot add this language to the website, the issue is that Crowdin doesn't support the Kara-Kalpak language (on their free tier), hence we cannot add this language there.

You could reach out to Crowdin support and inquiry why there's no support for that language on the free tier.

> If you don't want to add it as a custom language, can we take the files locally and translate?

We use Crowdin as our localization/translation platform, so if the language is not supported there, it would require us to do hacky things within the repository. Adding the files locally only would break the standard and make things more complicated for us to maintain.

I know this is not what you were expecting, so I'm sorry :/

I'm closing this issue for now, as there's nothing we can do.
