### ISSUE TITLE
Bug: .idea folder is not present in .gitignore file

### ISSUE THREAD

**Issue by EmirBoyaci** [nodejs/nodejs.org#5093]
### URL:

https://nodejs.org

### Browser Name:

Arc

### Browser Version:

Chromium Engine Version 110.0.5481.177

### Operation System:

MacOS 13.2.1 (22D68)

### How to reproduce the issue:

I believe including .idea folder (which is automatically created by any JetBrains application if developer is using JetBrains products) in .gitignore file would makes more sense to not to have "unversioned files" section.

![Screenshot 2023-03-09 at 16 28 50](https://user-images.githubusercontent.com/59085992/224037481-cb60e12c-61d8-4064-b975-d98eac1acab1.png)

**Comment by Trott** [comment]
Repeating my comment in the PR that addresses this:

I would vastly prefer people add these kinds of things to their personal .gitignore files rather than to individual repositories. Every repository on the planet should not have to add every IDE's specific files (or .DS_Store files or....) But you should know about your IDE (and your operating system, in the case of .DS_Store). So you can put it in one place and solve the problem everywhere for yourself.

**Comment by okuryu** [comment]
I always use this Git configuration.

`~/.gitconfig`:
```gitconfig
[core]
	excludesfile = ~/.gitignore_global
```

`~/.gitignore_global`:
```
*~
.DS_Store
.idea
.vscode
```

See also GitHub's guide:
- https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer

**Comment by ovflowd** [comment]
Agreed with the previous comments from @Trott and @okuryu. This is not a bug from our side. Closing as not-planned.
