### ISSUE TITLE
Which translation platform to choose? Crowdin or GitHub directly?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#5139]
### Enter your issue on localizations here:

Nothing but just want to confirm about the translation platform: Crowdin or GitHub?

Now I'm using Crowdin with some translations updated without submitting through GitHub directly. However it seems some Crowdin PR are closed and most of md files are updated directly through GitHub...?

And what's more：There's something wrong with Crowdin when syncing, and is this fixed now? How frequently will the Crowdin synced with md files for translations now?

**Comment by ovflowd** [comment]
> Now I'm using Crowdin with some translations updated without submitting through GitHub directly. However it seems some Crowdin PR are closed and most of md files are updated directly through GitHub...?

Your translations don't get to GitHub because, on Crowdin, they're "QA". When you do a translation on Crowdin, they need to be proofread by someone with a "proofreader" rank. And then "published"; only then will Crowdin make a PR with the translations.

> And what's more：There's something wrong with Crowdin when syncing, and is this fixed now? How frequently will the Crowdin synced with md files for translations now?

Nothing is wrong; the issue is that Crowdin probably has its base branch outdated occasionally and tries to push source strings. I need to disable Crowdin from pushing source strings; that's it. (They get synced eventually)

**Comment by ghost** [comment]
OK, got it thanks!
