### ISSUE TITLE
How to keep "blog" page's localized for paging info without copying "blog" files from "en"?

### ISSUE THREAD

**Issue by ghost** [nodejs/nodejs.org#5188]
Now in each other localized folder we don't have 'blog', so when we go to 'blog' and switch from 'en' to any other languages, the page will still use the default English one.

Take 'zh-CN' as an example (we already have tranlated the related json file for "next"/"prev" and the title...ect, some paging info):
https://github.com/nodejs/nodejs.org/blob/add894a043b1ea20d69c7128ba121fb3a29b9a3d/i18n/locales/zh-cn.json#L35-L38

What I expect is:

![image](https://user-images.githubusercontent.com/52018749/227682254-ac01839a-4fb2-4343-8a77-cdf3c793ba02.png)

What I actually got is:
![image](https://user-images.githubusercontent.com/52018749/227682626-4450fbdc-f468-45e8-b942-d5306570a6ac.png)

Just as what I metioned above: We don't need "blog" folder in each other localized translations, which causes the problem and we've lost these pages as "token" for localization of paging info...ect.

So currently there're two solutions to it:

1. Keep what it is now, and **since we don't need to translate the "blog" part, we should remove all the codes related to "localization" in "blog" page, as well as those in localization (*.json) file.** 

E.g: "FormattedMessage" is duplicated, and it should be removed:
https://github.com/nodejs/nodejs.org/blob/add894a043b1ea20d69c7128ba121fb3a29b9a3d/components/Pagination.tsx#L7-L20

2. Get a full copy from 'en' and copy them directly into the other localization folder to make the md files as "token" for translation only (That's a bit too duplicated, too many copies of "blog"'s).

**Comment by ghost** [comment]
PS:

Firstly I don't think it's a bug, and of course it works properly if we don't have md files as "tokens", the default will be English ones, but that's wired to keep translation info for paging info and title without showing them onto the page.

So is there a better way for us to have "blog" in "en” only, but with localized info for paging info or title? 

I tend to vote for my point 1 (except that you've a better idea for it), and I'd be glad to help to do that. But before doing it, I need a confirm and voice from you.

**Comment by ovflowd** [comment]
Oh, boi, here we go again. Let me give you a TL;DR the "not copying" of localised files is a temporary solution until we adopt SSR on Next.js.

I appreciate you raising this concern, is yet another thing that was discussed during all the Next.js conversations, and I wonder if you just missed it or didn't realise we were talking about that.

I'm going to close this issue because this is already planned. If you have questions, please reach out on Slack.

**Comment by ovflowd** [comment]
Anyhow, going to drop another comment just with the "summary" of plans for the future:

1. Yes, folders that are not localised will fall back to English content with English localisation. This is expected and temporary.
2. The plan is first to migrate the Components, Layout and Content from nodejs.dev to nodejs.org before we plan on what to do with i18n—pretty much the already translated content from nodejs.dev will be reused here, too, when we port the content from nodejs.dev
3. Once all pages are migrated, the next significant effort will adopt SSR on our Next.js installation. At that point, we will probably already be on Vercel (Even if we're only using static generation).
4. The first part of work on the SSR part of Next.js will be to integrate middlewares and router capabilities for dynamic i18n routing. Meaning, Nextra/Next does the handling of i18n content.js
5. This allows us to remove the hacky i18n fallback config and localised 404 configs from our NGINX installation.
6. Ultimately, this will allow a similar behaviour to the one on nodejs.dev. If a specific page does not exist on a given locale, we will still serve that page with its respective i18n configuration, except that the content is not translated. (You can sneak peek at this behaviour on nodejs.dev)

There's a lot of work to be done, and SSR is something that we will probably handle only for around 1-3 months in the future.

So, this pretty much addresses your concerns. Let's not rush on creating issues about "now certain pages are not translated" and devise solutions that do not solve any problem. For future reference, @MaledongGit, I'd appreciate it if you'd keep an 👀 on all our discussions over time so that you're not left behind. As a team, we want to make decisions together, and when some team members don't know what's going on, it creates an awkward feeling that we're disorganised. Hence, please join Slack, keep an eye on discussions here (GitHub) and there, and let's coordinate our efforts. (So that you don't spend time on issues like these).

**Comment by ghost** [comment]
> I'm going to close this issue because this is already planned. If you have questions, please reach out on Slack.

@ovflowd：Sorry and it seems I've really missed up a lot of useful info..... And maybe the question is a bit "foolish". So where's the Slack and can I join in or to see your history?

**Comment by AugustinMauroy** [comment]
>  So where's the Slack and can I join in or to see your history?

https://slack.openjsf.org/ Chanel # nodejs-website

**Comment by ghost** [comment]
Thanks anyway! @AugustinMauroy

**Comment by ovflowd** [comment]
@MaledongGit no worries :) (I'm just trying to be mindful of everyone's time here)
