### ISSUE TITLE
Create <Time/> component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5481]
Create a generic `Time` cimponent that displays date info in the curent locale.

The component should have two props: `date`, which should be a string or `Date` object and the second one. corresponding to the shape of https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#options

The component should return a `time` element, with the DateTime formatted on the currently applied locale (so the component must use `useLocale` hook).

See the repeated usage of a workaround from https://github.com/nodejs/nodejs.org/pull/5479. The new component would replace these.

```jsx
<time dateTime={post.date}>
  {new Date(post.date).toLocaleString('en-GB', {
    timeZone: 'UTC',
    month: 'short',
    day: '2-digit',
  })}
</time>
```

**Comment by AugustinMauroy** [comment]
What do you thinks about using formattedDate ?

**Comment by ovflowd** [comment]
> What do you thinks about using formattedDate ?

Could you elaborate? `formattedDate` was a file on `util` that we removed because we got rid of `strftime` dependency, as it is not really needed. This issue simple entails about making a simple component.

**Comment by AugustinMauroy** [comment]
We don’t actually need a time commponent because react-intl furnish one 

in formattedDate we just need to intput date and nothing else because there are an intlProvider

**Comment by ovflowd** [comment]
> We don’t actually need a time commponent because react-intl furnish one

The implementation we're working on does not replace `react-intl`'s FormattedDate/FormattedTime Components.

While we could use `<FormattedDate>` to achieve a similar outcome as `toLocaleString`, it's important to note that `react-intl` utilizes `DateTimeFormat` underneath.

However, what you mentioned isn't entirely accurate because we're not duplicating `react-intl`'s functionality. Our intention is to create a reusable component that returns a `time` element.

If you refer to the documentation of `react-intl` (https://formatjs.io/docs/react-intl/components/#formatteddate), you'll find the following statement:

> This component uses the [formatDate](https://formatjs.io/docs/react-intl/api#formatdate) and [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) APIs and has props that correspond to the DateTimeFormatOptions specified above.

This aligns perfectly with our approach. While you could argue for using `<FormattedDate>`, both options achieve the same effect.

**Comment by AugustinMauroy** [comment]
A good point for react-intl is that we don't have to maintain it. It's an api of the package

**Comment by ovflowd** [comment]
> A good point for react-intl is that we don't have to maintain it. It's an api of the package

We neither need to maintain `toLocaleString`, @AugustinMauroy, it's part of EcmaScript specification. That's the point you're not getting.

Using `toLocaleString` and `FormattedDate` have the same options, same result, same outcome. Yet the only benefit of `FormattedDate` over `toLocaleString` is that we don't need to pass the locale code and call `useLocale`. (So it's a convenience)
