### ISSUE TITLE
Missing Logo Page

### ISSUE THREAD

**Issue by mcollina** [nodejs/nodejs.org#5545]
Once upon a time, we had a page that described our Logo:

http://web.archive.org/web/20211214054831/https://nodejs.org/en/about/resources/

Such a page is not available anymore, and those assets as well

**Comment by mcollina** [comment]
Note that there is https://nodejs.dev/en/about/branding/. The previous page should not have been removed without porting the new one.

**Comment by mcollina** [comment]
This was removed by @Trott in https://github.com/nodejs/nodejs.org/pull/4803. I think we should include the branding page as mentioned in the `.dev` website.

I think the website of the project is the place where to store our assets and branding guidelines.

**Comment by Trott** [comment]
Maybe let's link to https://github.com/openjs-foundation/artwork/tree/main/projects/nodejs instead of having a second copy on the website and needing to keep it in sync with any changes to that repo? (Although the logo hasn't changed in at least 4 years, so maybe keeping in sync is not that big of an issue.)

When I removed the original, it was because we were making the logo available as an Adobe Illustrator file (and not any other format), which I don't think we should do. That encourages people to modify the logo for their own purposes. We should make it available as a png and/or svg (or some other common format). That's the format in that repo, so linking there should be OK, but if we don't link there, let's at least use formats like those.

**Comment by omlondhe** [comment]
I want to contribute to this repository, may I work on this one?

**Comment by mcollina** [comment]
@Trott Note that https://nodejs.dev/en/about/branding/ includes quite a lot of other information that I think is _very_ useful beyond the logo itself (colors, accents, hexagons, etc). I recommend we move the page as-is.

I'm +1 on not distributing Illustrator files publicly. I'd like to know where those files are right now. Are we hosting them on a private repository?

@omlondhe sure, just wait a bit so we can agree on what to do.

**Comment by omlondhe** [comment]
Sure, works, I’ll wait till your decision on it.
Thank you for the opportunity!

Waiting…..

**Comment by Trott** [comment]
> @Trott Note that https://nodejs.dev/en/about/branding/ includes quite a lot of other information that I think is _very_ useful beyond the logo itself (colors, accents, hexagons, etc). I recommend we move the page as-is.

I don't have any problem with that. I have two additional things to be done below. It would be great if they could be taken care of before creating the page, but that's not strictly necessary. They can happen after the page is created too.

- [ ]  We should take the time to make sure that the contents of the .dev page does not conflict with any of the information in the README at https://github.com/openjs-foundation/artwork. We might want to include a link to the README but if not, then maybe reproduce a few key pieces of information such as this:

> Use of any trademark or logo is subject to the trademark policy available at https://trademark-policy.openjsf.org/. A list of the trademarks covered by this policy can be found at https://trademark-list.openjsf.org/.
> 
> Questions? Please email [trademark@openjsf.org](mailto:trademark@openjsf.org).

- [ ] We should confirm that we're still good to use/distribute versions of the logo on the .dev page that aren't also included in https://github.com/openjs-foundation/artwork/tree/main/projects/nodejs. (For example, the page on the .dev site includes a hexagon-on-the-right version. Is that approved for use? Or is that something we created ourselves and probably shouldn't use/distribute? I'm guessing it's fine as we use it on our website already, but you get the idea.) These kinds of questions can probably be referred to @kyliewd. I don't think we have legal-type questions that would go to the trademark@openjsf.org email above. Kylie might also have opinions on the advisability of us duplicating the artwork on our own site. (Maybe it's a great idea because that's where people will look for it. Maybe it's a not-so-great idea because the two sources will get out of sync. I'm fine with it myself. If it ever becomes a problem, we can just remove it again or make it  a redirect to the artwork repo page.)

**Comment by Trott** [comment]
> I'm +1 on not distributing Illustrator files publicly. I'd like to know where those files are right now. Are we hosting them on a private repository?

I'm pretty sure @kyliewd has them or else knows who does. (In an absolute worst case scenario, we can pull them out of old commits from this repository.)

**Comment by ovflowd** [comment]
Honestly, the colors on the Branding page on `nodejs.dev` are **not official** and are only part of the `nodejs.dev` repository. They're not official "brand colors".

This https://github.com/openjs-foundation/artwork/tree/main/projects/nodejs already has most of the artwork information needed, except the font family we use in the website (which honestly, I think it's irrelevant)

I'd rather have "Branding" redirect to the Artwork README for Node.js

**Comment by mcollina** [comment]
As long as it's linked from our website, then it's great.

**Comment by ovflowd** [comment]
@nodejs/nodejs-website we should add a logos page back and we could probably move the mascot SVG to that page. Anyone interested on working on that?

**Comment by AugustinMauroy** [comment]
@ovflowd I'd worked on the nodejs.dev one, so I'm interested in working on that.
