### ISSUE TITLE
Create `Button` component

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#5758]
Create a `Button` component using the new [figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=423-28019&mode=design&t=q5ACW63em8GjhzrV-4). 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

---

### Details

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/e5968cf9-faf7-4276-937c-f8235705132a)

❓ [Not sure where to start breaking down the figma? Read this short guide](https://github.com/nodejs/nodejs.org/discussions/5131#discussioncomment-6848378)

- Create a new directory called `Button` within the [`Common` directory](https://github.com/nodejs/nodejs.org/tree/main/components/Common) that contains all the new code.
- Use the new tailwind color and typography system to assign properties. For example, `Primary, Light, Default` uses `Green/600` per the figma.
- Add a storybook story file `components/Common/Button/index.stories.tsx` which exercises each of the button's states.

There are 24 states to capture within styles and stories:

#### Light

- Primary, Light Default
- Primary, Light, Hover
- Primary, Light, Focus
- Primary, Light, Disabled
- Secondary, Light, Default
- Secondary, Light, Hover
- Secondary, Light, Focus
- Secondary, Light, Disabled

#### Dark

- Primary, Dark, Default
- Primary, Dark, Hover
- Primary, Dark, Focus
- Primary, Dark, Disabled
- Secondary, Dark, Default
- Secondary, Dark, Hover
- Secondary, Dark, Focus
- Secondary, Dark, Disabled

#### Special

- Primary, Special, Default
- Primary, Special, Hover
- Primary, Special, Focus
- Primary, Special, Disabled
- Secondary, Special, Default
- Secondary, Special, Hover
- Secondary, Special, Focus
- Secondary, Special, Disabled

**Comment by umairraza96** [comment]
I would like to work on this

**Comment by umairraza96** [comment]
@bmuenzenmeyer @ovflowd  What do you think about integrating [`cva`](https://cva.style/docs) for making variants a little bit easier for button component, it may also help streamlining the creation of other components which might have variants.

I would also like mention [`tailwind-merge`](https://github.com/dcastil/tailwind-merge) and [`clsx`](https://github.com/lukeed/clsx) which are helping libraries to mitigate the complexities while using tailwind with conditional statements.

**Comment by bmuenzenmeyer** [comment]
I'm open to whatever tooling we need that:

- is not duplicative with current choices
- helps maintain our designs
- has little to no negative impact on end-user experience
- is well-maintained and stable itself

also read the [dependency pinning guide](https://github.com/nodejs/nodejs.org/blob/main/DEPENDENCY_PINNING.md) for more details.

I've used libraries like this before, such as `classnames`, and agree their utility is great. I don't have a direct TW experience, so I'll defer a bit to your comment as to why they are needed. I assume merging the TW directives gets messy. Can you provide a short example proving this out?

---

edit: or, in your PR, you could write it the inefficient way and then we'd have a direct application of where the library could be useful

**Comment by umairraza96** [comment]
So these packages offers utilities in order to make working with tailwindcss much easier
 - **cva** or class-variance-authority insures typesafety like it will produce types for variants and other configs if defined otherwise we'll have to write types ourselves in other words variants with `string` props won't give us autocomplete features of typescript while cva will enable us to have autocomplete with our variants. 
 
 - **twMerge** offers merging without conflicts easier e.g: for instance you have defined padding for the component and for some reason you want to change it at a specific location. you would simply add className with the new padding and it will override the component's but the catch is it often times it doesn't override if it overrides at all, this is where `twMerge` comes into play and it makes sure that the passed down padding through className overrides the padding of the component. [readmore](https://github.com/dcastil/tailwind-merge/blob/v1.14.0/docs/what-is-it-for.md#thanks-but-i-prefer-to-read)
 - **clsx** I think `classnames` is pretty similar to `clsx`. I have never used classnames. I have only used `clsx`. I'll do a little more research on this one.

**Comment by umairraza96** [comment]
It seems to me that we do not need `clsx` as it is similar to `classnames` with better performance and smaller size.

**Comment by ovflowd** [comment]
I'd rather reduce the amount of added packages if they bring little benefit. I feel that just `classnames` is more than enough for variants... I assume. It introduces of course a little bit more verbosity, but I'm fine with that.
