### ISSUE TITLE
chinese homepage

### ISSUE THREAD

**Issue by susongyan** [nodejs/nodejs.org#579]
i visit the chinese homepage of node,  but it  only shows the menu in chinese    .    Can I help to translate it in  Chinese  and How?

**Comment by benjamingr** [comment]
@nodejs/nodejs-cn

**Comment by susongyan** [comment]
404   ~

**Comment by benjamingr** [comment]
@minorpoet I pinged people so they see your post - it'll take a little bit :)

**Comment by stevemao** [comment]
@minorpoet the Chinese repos sit at https://github.com/nodejs/nodejs-zh-CN and https://github.com/nodejs/nodejs-zh-TW

**Comment by susongyan** [comment]
thanks  : )

**Comment by laosb** [comment]
@minorpoet which "chinese homepage"?

**Comment by stevemao** [comment]
I'm gonna close this but you guys can keep talking.

**Comment by susongyan** [comment]
@laosb  http://nodejs.cn/

**Comment by ttxs25830** [comment]
> @laosb http://nodejs.cn/

Is this site official? I see many content need VIP to read. I thought it was unofficial cause don't see an VIP interface on English official site and this site even don't support HTTPS

**Comment by std4453** [comment]
Sorry for the interruption, but https://nodejs.cn has some major problems with it.

1. It contains advertisement, and when you use an adblocker, it alerts "Please do not block ads on this site!" (translated from Chinese, original text is "请勿屏蔽本站广告！") and refreshes the site, preventing you from reading the documentations. Hilarious as it might seem, the site tries to load a script from https://cdn.wwads.cn/js/makemoney.js , a perfect name to show the maintainer's true intentions.
2. It appears at first place in Google search results (https://www.google.com/search?q=corepack), above the official nodejs.org documentation. This might be related to my language preferences, but this is highly misleading for general users, probably hurting the Node.js organization by making people believe that it's a commercial project.
3. Uses the Node.js logo, as hosted under https://img.nodejs.cn/logo.svg and visible on (https://nodejs.cn), and due to the commercial nature of this site, I believe such usage is against the Node.js trademark policy, as seen at https://nodejs.org/en/blog/uncategorized/trademark and https://images.prismic.io/openjsf/69641abf-ac84-44a2-b719-ee4498d07b06_OpenJS-Foundation-Trademark-Policy-2021-01-12.docx.pdf:
   >  Do not use logos or names of the OpenJS Foundation in any commercial or marketing context other than as expressly permitted in this policy unless you have obtained explicit written permission from the OpenJS Foundation to do so.

Regarding the aforementioned facts, I suggest that a DMCA takedown be issued on this site, or that an official claim being made to Google (https://support.google.com/legal/answer/3110420?hl=en&authuser=0), so that it could disappear from Google search results, preventing further harm from being done to the Node.js community, its contributors, and the OpenJS Foundation.

I would be more than willing to provide whatever help necessary to make this happen, and if this isn't right place to talk about the matter, I'm happy to switch forms of communication. You can reach me at me@std4453.com.

**Comment by ovflowd** [comment]
> Sorry for the interruption, but [nodejs.cn](https://nodejs.cn) has some major problems with it.
> 
> 1. It contains advertisement, and when you use an adblocker, it alerts "Please do not block ads on this site!" (translated from Chinese, original text is "请勿屏蔽本站广告！") and refreshes the site, preventing you from reading the documentations. Hilarious as it might seem, the site tries to load a script from [cdn.wwads.cn/js/makemoney.js](https://cdn.wwads.cn/js/makemoney.js) , a perfect name to show the maintainer's true intentions.
> 2. It appears at first place in Google search results ([google.com/search?q=corepack](https://www.google.com/search?q=corepack)), above the official nodejs.org documentation. This might be related to my language preferences, but this is highly misleading for general users, probably hurting the Node.js organization by making people believe that it's a commercial project.
> 3. Uses the Node.js logo, as hosted under [img.nodejs.cn/logo.svg](https://img.nodejs.cn/logo.svg) and visible on ([nodejs.cn](https://nodejs.cn)), and due to the commercial nature of this site, I believe such usage is against the Node.js trademark policy, as seen at [nodejs.org/en/blog/uncategorized/trademark](https://nodejs.org/en/blog/uncategorized/trademark) and [images.prismic.io/openjsf/69641abf-ac84-44a2-b719-ee4498d07b06_OpenJS-Foundation-Trademark-Policy-2021-01-12.docx.pdf](https://images.prismic.io/openjsf/69641abf-ac84-44a2-b719-ee4498d07b06_OpenJS-Foundation-Trademark-Policy-2021-01-12.docx.pdf):
>    > Do not use logos or names of the OpenJS Foundation in any commercial or marketing context other than as expressly permitted in this policy unless you have obtained explicit written permission from the OpenJS Foundation to do so.
> 
> Regarding the aforementioned facts, I suggest that a DMCA takedown be issued on this site, or that an official claim being made to Google ([support.google.com/legal/answer/3110420?hl=en&authuser=0](https://support.google.com/legal/answer/3110420?hl=en&authuser=0)), so that it could disappear from Google search results, preventing further harm from being done to the Node.js community, its contributors, and the OpenJS Foundation.
> 
> I would be more than willing to provide whatever help necessary to make this happen, and if this isn't right place to talk about the matter, I'm happy to switch forms of communication. You can reach me at [me@std4453.com](mailto:me@std4453.com).

Yeah this is not an official Website afaik. I'll talk with the Foundation
