### ISSUE TITLE
Download (LTS) page not displaying

### ISSUE THREAD

**Issue by jd-foster** [nodejs/nodejs.org#6024]
### URL:

https://nodejs.org/en/download

### Browser Name:

Firefox, Safari

### Browser Version:

118.0.2 (Firefox), 17.0 / 17616.1.27.111.22 (Safari)

### Operating System:

Mac 12.7

### How to reproduce the issue:

Clicking on the "DOWNLOADS" link at top of page:

<img width="1228" alt="image" src="https://github.com/nodejs/nodejs.org/assets/38274066/6114cec4-6816-4f40-8b19-58165cc8c669">

Note that `https://nodejs.org/en/download/current` shows fine,
<img width="1326" alt="image" src="https://github.com/nodejs/nodejs.org/assets/38274066/cc27a754-065c-491c-9eb5-7a7d45d46b7d">

but clicking on the "LTS" reproduces it.

**Comment by jd-foster** [comment]
No idea if this is helpful, but the browser error is:
```
Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 9
[framework-4b72473691bcf94b.js:9:46879](https://nodejs.org/_next/static/chunks/framework-4b72473691bcf94b.js)
```

**Comment by bmuenzenmeyer** [comment]
looking into this - though without vercel access i can not roll back

edit: not rendering locally, but also not erroring
edit2: hydration error
edit3: previews from days and days ago are failing, so this has either been broken for some time or there is a dynamic element

**Comment by bmuenzenmeyer** [comment]
this is happening because there is not currently a release that qualifies as an active LTS. The code is working as designed - the input is bad (garbage in, garbage out) 

In `node-releases-data.json`

```diff
  {
    "major": 20,
    "version": "20.8.1",
    "codename": "",
    "currentStart": "2023-04-18",
-   "ltsStart": "2023-10-24",
+   "ltsStart": "2023-10-16",
    "maintenanceStart": "2024-10-22",
    "endOfLife": "2026-04-30",
    "npm": "10.1.0",
    "v8": "11.3.244.8",
    "releaseDate": "2023-10-13",
    "modules": "115"
  },
```

restores the data

![image](https://github.com/nodejs/nodejs.org/assets/298435/3d0861fb-f684-49b5-bdaa-6e7fd0833bfa)


---

that's not likely the correct solution, as I'd assume Node 18 should be LTS for another week.

but according to https://github.com/nodejs/Release we actually in a donut-hole of LTS support?

![image](https://github.com/nodejs/nodejs.org/assets/298435/806724ab-6d98-4c19-aedc-a8843494f894)
![image](https://github.com/nodejs/nodejs.org/assets/298435/5b3c2bea-8378-4ac4-9e4e-9bec2f67976d)

**Comment by ovflowd** [comment]
cc @nodejs/releasers @nodejs/build this is not the first time website breaks because of no current active LTS...

**Comment by ovflowd** [comment]
Also asking to @nodejs/releasers if there is no active LTS release, what should we render?

**Comment by targos** [comment]
The website doesn't specifically say it's in Active state. I would always render the one with the highest major version number, so 18.x

**Comment by ovflowd** [comment]
> The website doesn't specifically say it's in Active state. I would always render the one with the highest major version number, so 18.x

Right, that makes sense. Just wanted to confirm.

@bmuenzenmeyer are you still around? Sadly Im not close to my PC now.
