### ISSUE TITLE
Restore the `NODE_MODULE_VERSION` and v8 version columns on the previous releases page

### ISSUE THREAD

**Issue by zbjornson** [nodejs/nodejs.org#6188]
### Enter your suggestions in details:

The new [previous releases](https://nodejs.org/en/about/previous-releases) page no longer shows the `NODE_MODULE_VERSION` or v8 version for each release. Those were super useful for native module maintainers, and I don't see anywhere else that that info is listed nicely across releases. Can those columns be restored please?

**Comment by ovflowd** [comment]
> ### Enter your suggestions in details:
> The new [previous releases](https://nodejs.org/en/about/previous-releases) page no longer shows the `NODE_MODULE_VERSION` or v8 version for each release. Those were super useful for native module maintainers, and I don't see anywhere else that that info is listed nicely across releases. Can those columns be restored please?

These columns are likely not going to be added due to the Website Redesign. Please refer to https://github.com/nodejs/nodejs.org/discussions/5131;

Also IMO, the Website is mostly tailored for end-users, I doubt that's the right place where we should mention N-API versions and such. The data containing the N-API versions is provided within https://nodejs.org/dist/index.json

**Comment by ovflowd** [comment]
Closing as there wasn't a reply from the author.

**Comment by gibfahn** [comment]
> Also IMO, the Website is mostly tailored for end-users

For what it's worth as an end-user, I came to the releases page looking for a `NODE_MODULE_VERSION` list because I'm debugging an error of the type:

```
The module '<path>' was compiled against a different Node.js version using
NODE_MODULE_VERSION 127. This version of Node.js requires
NODE_MODULE_VERSION 115. 
```

and I need to know what versions of node they correspond to.

All the search results I can find for `NODE_MODULE_VERSION` point to the releases page as the place to get this info, so it was a bit surprising to find it had been removed.

**Comment by ovflowd** [comment]
> > Also IMO, the Website is mostly tailored for end-users
> 
> 
> 
> For what it's worth as an end-user, I came to the releases page looking for a `NODE_MODULE_VERSION` list because I'm debugging an error of the type:
> 
> 
> 
> ```
> 
> The module '<path>' was compiled against a different Node.js version using
> 
> NODE_MODULE_VERSION 127. This version of Node.js requires
> 
> NODE_MODULE_VERSION 115. 
> 
> ```
> 
> 
> 
> and I need to know what versions of node they correspond to.
> 
> 
> 
> All the search results I can find for `NODE_MODULE_VERSION` point to the releases page as the place to get this info, so it was a bit surprising to find it had been removed.

I suppose we could add that information back to the table.

**Comment by gibfahn** [comment]
Looks great, thanks for re-adding it!
