### ISSUE TITLE
Missing Redirects for certain migrated Guides

### ISSUE THREAD

**Issue by ovflowd** [nodejs/nodejs.org#6338]
A lot of guides (`/en/docs/guides`) got migrated to the new Learn section (`/en/learn`), but no redirects are set in place from the old links to the new ones. Causing 404s on several of them.,

This issue is about finding the guides that got migrated (git history) and setting up redirects for them on `redirects.json` as it has already been done for a few of them.

**Comment by mikeesto** [comment]
I'm a bit confused because https://github.com/nodejs/nodejs.org/blob/main/redirects.json#L187-L190 looks like it has already been setup for Flame Graphs - but the URL that has been crawled by Google (if you search for "node diagnostic flamegraphs") is https://nodejs.org/en/guides/diagnostics-flamegraph which still leads to a 404 currently. There is no `/docs/` in the URL

**Comment by mwenku** [comment]
@mikeesto the previous issues didn't mention adding redirects for every migrated guide. I belive most of them if not all, were migrated without adding redirects for the old links.  Could be nice if the current/future Migration issues could be updated to also mention adding redirects. for the migrated guide. I can mention this issue on the past issues that don't have PRs though. What do you all think?

**Comment by ovflowd** [comment]
Indeed. @bmuenzenmeyer could you update the issues, since you've created'em?

**Comment by AugustinMauroy** [comment]
Claudio there are still links that are not covered by the redirection?

**Comment by ovflowd** [comment]
🤷

We can close this for now
