### ISSUE TITLE
Inaccurate mobile/responsive breakpoint leads to horizontal scrolling on medium screen widths

### ISSUE THREAD

**Issue by uncenter** [nodejs/nodejs.org#6399]
### URL:

https://nodejs-hwdsshiko-openjs.vercel.app/en

### Browser Name:

Arc (Chromium)

### Browser Version:

122.0.6261.94 (Official Build) (arm64) 

### Operating System:

macOS Sonoma 14.3.1

### How to reproduce the issue:

![Screenshot 2024-03-02 at 13 22 03 (Arc)](https://github.com/nodejs/nodejs.org/assets/47499684/476da2ac-e9bf-49cc-8c51-f70fb1e50f2e)
The breakpoint appears to be at 768px when it should be at about 1000px.

**Comment by ovflowd** [comment]
I wouldn't consider this an issue. Since this only happens with very specific sizing/resizes that usually need to be more natural.

We've tested on numerous viewports for mobile devices, tablets, small form factor screens, large and extra large screens. There will always be a specific width where the breakpoints might get a bit scuffed/inaccurate.

I'm open on having this fixed, but I myself wouldn't spend any time on fixing this, since it's (at least in my definition) quite corner-case 🤔 

I'll keep this open if anyone feels like tackling this issue.

**Comment by uncenter** [comment]
True indeed! I'd just thought I'd mention it though, not sure where exactly this is set but it seems like a relatively easy fix?

**Comment by ovflowd** [comment]
> True indeed! I'd just thought I'd mention it though, not sure where exactly this is set but it seems like a relatively easy fix?

It might be, haven't investigated it. Anyone is welcome to contribute :)

**Comment by Nyx1on** [comment]
> > True indeed! I'd just thought I'd mention it though, not sure where exactly this is set but it seems like a relatively easy fix?
> 
> It might be, haven't investigated it. Anyone is welcome to contribute :)

Should we change the breakpoint to 1000px?
