### ISSUE TITLE
Meta: Enable learn translation 

### ISSUE THREAD

**Issue by AugustinMauroy** [nodejs/nodejs.org#6429]
On [crowdin config](https://github.com/nodejs/nodejs.org/blob/193256398b352ac709dfa2c7afdab8e27367c357/crowdin.yml#L11) there are ligne to ignore translation of lear section.

We should enable translation for theses useful resources.

**Comment by ovflowd** [comment]
No. It's intentional that we're not translating learning materials. It's just too much content, too technical and practically impossible to revise.

We went over this already in the past ;)

**Comment by bmuenzenmeyer** [comment]
This was brought up again by two different translators in Crowdin. I am going to temporarily re-open so we can discuss a bit more long-form.

**Comment by bmuenzenmeyer** [comment]
Let's try to tackle these one by one.

- `too much content`
- `too technical`
- `impossible to revise`

`Too much content`: Agree there is a lot. Crowdin has no limits on the number of translators, and they keep wanting us to try AI-assisted translation. Perhaps this is now more feasible.

`too technical`: To me, the whole site is technical, 😅 Agree, though, that lot's of the content has code examples.

`impossible to revise`: I'm not sure what you mean here. I agree we have had trouble getting English revisions to the content, so  it'd be bad to translate stale content.

**Comment by ovflowd** [comment]
It was a TSC decision to block translation of technical content. We talked about this during TSC meetings.

cc @mcollina as he has some context; i.e. that technical content should not be translated as the context can be easily lost and keeping the translations up to date is complicated. Even if one translator from one language says that they would maintain it, there's no guarantee that they will actually translate it regularly NOR we can confirm that the translations are correct, and since learn material and API docs are sensitive content, it's important that they are correctly proofreader.

I don't believe AI translation would also be any helpful here. + I doubt the TSC would approve usage of AI Translators to translate the content of the Website. Remember, we the Website team have no say on the content.

**Comment by bmuenzenmeyer** [comment]
Thanks for the additional detail.  That helps resolve the matter more authoritatively.

**Comment by ovflowd** [comment]
I'm more than happy to revise this or bring the conversation again to the TSC, but I would rather have more people first acknowledging interest in maintaining such documents, or maybe more arguments.

**Comment by mcollina** [comment]
While I'm opposed in translating the content of the apis section, I'd be neutral of translating the `learn` section, because its content is mostly stable over time.

**Comment by ovflowd** [comment]
cc @bmuenzenmeyer based on Matteo's reply here, do we want to bring this to the TSC for consensus?

**Comment by bmuenzenmeyer** [comment]
this topic was brought up again within https://github.com/nodejs/nodejs.org/discussions/7028 and https://github.com/nodejs/nodejs.org/pull/7001

can we revisit this?

**Comment by AugustinMauroy** [comment]
any news on revisit the question ?

**Comment by bmuenzenmeyer** [comment]
i'd like to start creating a list of instances

#### GitHub

https://github.com/nodejs/nodejs.org/pull/7345

#### Crowdin

> As the title says, why can't we translate those articles?

> It was said that since the content itself changes a lot, it could be difficult the work of keeping it updated on the translated versions.
>  I do not like the defended points, because I translated the content of learn section on nodejs.dev project, but I can not say that their reasons are totally bad.

>I think those articles are more worth translating compared to others. Maybe we should consider translating them.
> If we are concerned about updates not being timely, maybe we should consider adding a warning label instead of not translating.

>So can we take the documents in that repository at https://github.com/nodejs/nodejs.org/tree/main/apps/site/pages/en, translate them ourselves, and publish and share the site for non-profit purposes?

**Comment by AugustinMauroy** [comment]
I think we should properly document the fact that we don't accept translations on the learn section. Because the source content is not up to date with the current runtime. And that we don't have a correct Learning Graph. But as soon as the learn section has the right shape and is well maintained, let's gooooo for translating it.

**Comment by ovflowd** [comment]
It is essential to mention that translating those sections is not a Website Team decision. The TSC was against that, and we should abide by that decision. I don't want to have us second-guessing our decisions and revisiting them every three or whatnot months. This is starting to get annoying.

So yes, we should document all the reasonings + the fact that it was a TSC decision.

**Comment by ovflowd** [comment]
Returning to Matteo's last comment, most of the decisions were for the API docs. So, whether we want to change our decision for the learn section or abide by our current decision, we should decide.

I am still against translating the "learn" content. If the current Crowdin integration has shown me anything, we, the maintainers, barely monitor the content and are primarily first responders when we see issues. We have no idea what the translated content is, and we have no trusted proofreaders.

Plus, it is technical content, and I see it as being hard to deliver and translate correctly; if our current translators are not even able to identify Markdown links and do them correctly, I cannot trust that they will at this moment have the technical understanding (and depth) of what the learning content means to be able to convey on their native languages properly. The "learn" content must be translated to respect the original author's intent, wording, and meaning.

It is a tricky situation, and the learning content has much to translate; I would rather have no translations than partial or halfback translations. We don't have the resources of translators, proofreaders, or maintainers time to verify these translations. And having these translations wrong is way more impactful than just a mistranslated "Download" button.

I'm strongly -1, but it is not my decision but a consensus. Please prove me wrong because, ideally, I definitely want this content to be translated. But I don't think it can at this moment.

**Comment by Eutalix** [comment]
I understand the challenges faced by the community in translating the "learn" section, but I believe that relying on automatic translation tools like Google Translate might not be the best option for learners. While these tools can help, they often result in inaccuracies or confusing translations that could hinder understanding, especially with technical content.

Between using Google Translate and relying on official translations, I believe the official route is the better option. Official translations tend to be more reliable because they are done by people who have a deeper understanding of the terminology and context. Even though I use AI for translations myself, I make sure to review and adjust them to ensure that the content accurately reflects the intended meaning.

It would be beneficial to trust community translators who are familiar with the technical language and have experience working on official translations. Selecting contributors who have already helped with translations could help maintain quality and consistency.
