### ISSUE TITLE
Pre-built binary download link for Linux X64 is incorrect on official site

### ISSUE THREAD

**Issue by copyrighthero** [nodejs/nodejs.org#6613]
### URL:

https://nodejs.org/en/download/prebuilt-binaries

### Browser Name:

Firefox

### Browser Version:

124.0.1

### Operating System:

MacOS Sonoma 14.4.1

### How to reproduce the issue:

1. Navigate to the pre-built binary download page, and select Linux and X64.
2. The download link is `https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-64.tar.xz`, which does not exist; the correct link should be `https://nodejs.org/dist/v20.12.1/node-v20.12.1-linux-x64.tar.xz`; there is a missing `x` before 64.
3. I did not verify other download links.

**Comment by canerakdas** [comment]
Thank you for reporting this bug, I have prepared a PR for fixing this issue; #6614

**Comment by mn4367** [comment]
The same happens on a Mac with an M1 chip. Opening the page in Safari or Firefox offers to download the `x64` version instead of `ARM64` and the download link is broken. Switching the combobox one time to `ARM64` and then back to `x64` 'fixes' the download link. In Chrome everything seems to be OK.

![Bildschirmfoto 2024-04-12 um 12 06 55](https://github.com/nodejs/nodejs.org/assets/6379696/30b1dfa2-6c01-40f5-890a-d1e7e3c24d35)
