### ISSUE TITLE
Add a page to the website to talk about how Node.js work is funded

### ISSUE THREAD

**Issue by wesleytodd** [nodejs/nodejs.org#6616]
### Enter your suggestions in details:

1. A top level navigation link to this page
2. Links to lfx funding platform
3. Links to individual contributors GH sponsors pages
4. Other ideas?

**Comment by Qard** [comment]
Worth including subsystem focus areas for each listed contributor so prospective sponsors can find people that would be good to sponsor to work on a particular feature or fix.

**Comment by mcollina** [comment]
I think we could list member companies that can be hired to fix bugs / that are available for hire (and how to contact them).

**Comment by AugustinMauroy** [comment]
> Links to individual contributors GH sponsors pages

I'm a bit reluctant about this because you have to say yes, it exists but I don't think the role of the node site is to say "come and support Matteo Collina and other".

**Comment by wesleytodd** [comment]
> but I don't think the role of the node site is to say "come and support Matteo Collina and other".

I would be interested in why you might feel this way? Could you tell me a bit more about why you are concerned about doing this part?

**Comment by AugustinMauroy** [comment]
> I would be interested in why you might feel this way? Could you tell me a bit more about why you are concerned about doing this part?

I don't think we should single out any particular person, because we need to promote means of support and not single out one person in particular.

**Comment by bmuenzenmeyer** [comment]
I'm altogether curious about how this would play out. I can see how it subtly changes the mood of the project. 

> Links to lfx funding platform

no doubt, we get support via the openjs foundation and we state that in our [readme](https://github.com/nodejs/node/blob/main/README.md#nodejs) and by association in the footer. agree it's not too clear

I'd think we'd also list people funding with material donations, such as [website technology donations](https://github.com/nodejs/nodejs.org?tab=readme-ov-file#thanks), GH Actions servers, time from employers...

> Links to individual contributors GH sponsors pages

I think the hesitancy comes from how many questions this opens up. Of course we all want recognition for the value we bring the project, in each of our ways. Right now, it's intrinsic and intangible. Where I get a bit lost is points 2 and 3 in @wesleytodd's OP span two separate ideas. We go from "let's talk about how Node.js is funded" to "let's fund maintainers". Perhaps we hope to link them.

How do we govern who qualifies? I imagine their will be a lot of FOMO. Is there a threshold? only TSC? If I land a website feature should i get compensated? If I landed a set of features years ago, but have become dormant, do i continue getting funds? Does someone audit that? Link it to collaborator status?

Suggest it would it be better research an open collective with donations and the ability to transparently expense from the fund. 
Does openjs have any thoughts on this, since they are providing funds? i've been generally curious. I've heard of folks wanting to donate to node.js before, but the only current mechanism is to donate to LF and hope for"trickle-down". This might be my own naivety, so please forgive me.

For reference, eslint is an openjs project that has an opencollective presence. Check out https://eslint.org/donate/ - maybe that would work. 
They break out a ton of cool things, enabled by the fund

- team development, TSC rate and reviewer rate per hour
- contributor pool for outside collaborators making significant contributions
- dependencies
- community projects
- support systems

Or maybe we break out this issue into the two separate work streams. 

1. Acknowledge our supporters.
2. Open pathways to fund our maintainers.

> list member companies

what is a member company? the only mention of a company i can find on the core readme is under [release stewards](https://github.com/nodejs/node/blob/main/README.md#security-release-stewards) - but that sounds different in intent

> I think we could list member companies that can be hired to fix bugs / that are available for hire (and how to contact them).

[Some projects are pretty blunt about it](https://www.11ty.dev/super-professional-business-network/) 😄 

----

I'm just on the website team. Content decisions are not ours to make.

**Comment by wesleytodd** [comment]
I didn't post context, but I opened this while at the Collab Summit last week where this was an active part of the conversation. The goal was to have that conversation so we could decide it if was a good path forward. Thanks for engaging on this conversation.

> I don't think we should single out any particular person, because we need to promote means of support and not single out one person in particular.

But we are all single individuals. I personally am very comfortable telling people to directly pay every single individual who has ever shown up to contribute to Node.js for a substantial amount of time. Maybe we don't drop links for everyone, but it feels like we can easily say "if you are a collaborator or on the TSC" then you can be on the page. I personally even feel comfortable breaking down each active WG and listing the members who also accept funding, but we could do those separately if it was controversial.

> no doubt, we get support via the openjs foundation and we state that in our [readme](https://github.com/nodejs/node/blob/main/README.md#nodejs) and by association in the footer. agree it's not too clear

I feel like this part is not controversial? So should we maybe separate that out into a single issue/PR to make that happen?

> Right now, it's intrinsic and intangible. Where I get a bit lost is points 2 and 3 in @wesleytodd's OP span two separate ideas. We go from "let's talk about how Node.js is funded" to "let's fund maintainers". Perhaps we hope to link them.

In addition to my point in response to @AugustinMauroy, I think this is a natural transition. The maintainers *are the project*. Funding them is funding the project (full stop).  I know it can get prickly with money involved and we would want to make very clear guidance, but IMO this is a logical step in the goal to fund the work.

> If I land a website feature should i get compensated?

To be clear, my suggestion is to feature individual contributors not fund specific work. I believe that we should *also* fund specific work however we can, but that is not the goal of "feature GH sponsors for individual contributors" is intended to solve. If an IC does list "here are bugs/features you can pay me to work on" on their GH sponsors page that would be cool, but that is up to individuals and the groups wanting to pay for that work.

> Or maybe we break out this issue into the two separate work streams.

Yeah, seems like maybe we would need 3 even?

**Comment by AugustinMauroy** [comment]
> In addition to my point in response to @AugustinMauroy, I think this is a natural transition. The maintainers are the project. Funding them is funding the project (full stop). I know it can get prickly with money involved and we would want to make very clear guidance, but IMO this is a logical step in the goal to fund the work.

I'm with you on this idea. But how do you tell who can be on this page and who can't? For example Claudio hasn't contributed to node core yet but he deserves a place on this page if he wants it.

I'm not saying I'm against it, but I think we need to be careful about how we go about it.

**Comment by wesleytodd** [comment]
> I'm with you on this idea. But how do you tell who can be on this page and who can't? For example Claudio hasn't contributed to node core yet but he deserves a place on this page if he wants it.
> 
> I'm not saying I'm against it, but I think we need to be careful about how we go about it.

Totally agree! I would love to feature any folks who make significant contributions across the project in a holistic way. That certainly means Claudio and a lot of other folks in similar situations.

**Comment by bmuenzenmeyer** [comment]
> I didn't post context, but I opened this while at the Collab Summit last week

I suspected as much from the timing, and that it looked like a quick jot down of ideas. I hope my comments were not seen as a 👎 - moreso that we need to be intentional about how we go about it.

@wesleytodd et all, I've broken this conversation up into two separate stories.

**Comment by wesleytodd** [comment]
Awesome! Yes that was exactly it, to make sure we didn't forget to follow up in the issues on it. Thanks for breaking up into more focused issues, that is a great next step. Do we want to close this and use those?
