### ISSUE TITLE
Re-brand "Stable" channel to "Current"

### ISSUE THREAD

**Issue by mikeal** [nodejs/nodejs.org#669]
There's been pretty wide agreement that we should do this for some time, we should pull the trigger before the v6 release.

**Comment by MylesBorins** [comment]
I'm +1 on this. Who needs to sign off on a change this big? @nodejs/tsc? @nodejs/ctc?

**Comment by mscdex** [comment]
Did we decide on the name "Current?"

**Comment by MylesBorins** [comment]
fwiw I'm +1 on a change... I'm up for whatever and will avoid getting into the naming bike shed. 

"Stable" in particular has been causing some misconceptions.

**Comment by evanlucas** [comment]
I like "Current"

**Comment by mikeal** [comment]
@mscdex we have several other threads, mostly around the LTS branding, where we talked about this. A lot of those threads are side tracked by proposing re-branding LTS (which we decided not to do and survey results show that people actually do understand it pretty well) but having "Stable" and "LTS" is still confusing especially when it just isn't accurate.

**Comment by mikeal** [comment]
oh, also, _many_ other projects use the term "Current" for exactly what we're using it for.

**Comment by kahwee** [comment]
"Current" seems to be a better word indeed, since "LTS" is stable too.

**Comment by ghost** [comment]
+1 because 'stable' is confusing. LTS is 'stable' too

**Comment by ghost** [comment]
also i have a bit of free time, so once this is signed off, can i make the PR?

**Comment by jasnell** [comment]
This is fine. I can add this into the release but since v6 is going out before the next CTC call we'll need to get agreement here. /cc @nodejs/ctc

**Comment by Trott** [comment]
I have always found our usage of `Stable` problematic and am in favor of `Current` as a replacement.

**Comment by mikeal** [comment]
go ahead and prepare a PR and we can get whatever signoff necessary.

**Comment by MylesBorins** [comment]
on it

**Comment by MylesBorins** [comment]
@mikeal So I sent this simplest PR which is to update the docs in the main repo

We will also have to update the site, I think it might make sense for @fhemberger to handle that or at least someone more familiar with the code base as the word "stable" is used not only in the copy, but in css selectors and hard coded within the tests. That being said I think we should get 100% sign off before that work is done.

As far as I can tell there is nothing that needs to be updated in `/download`, but perhaps someone from @nodejs/build can verify that for me.

We will also have to update the copy in https://github.com/nodejs/lts

Turns out there is only a single reference to `stable`, but we'll need to also update the graphic (do you know where that lives @mikeal?). If I can get a copy of a psd or illustrator file I can update that

Those are just the references I knew off the top of my head, I'll do a more in depth search after we get sign off.

**Comment by fhemberger** [comment]
I prepared a PR for this in #672, please have a look …

**Comment by ChALkeR** [comment]
+1 on this change.

**Comment by mhdawson** [comment]
+1 on this change.

**Comment by Fishrock123** [comment]
I'm still **not** ok with this if it ~~directly~~ leads to LTS being called Stable. The Stable/Current release line(s) are intended and maintained so as to be usable, and are not to be taken as experimental. If you want experimental, that is nightlies.

Additionally, if LTS renames to Stable, it's going to be a hell of a time whenever someone looks back at discussions and tries to decipher exactly what we are talking about.

**Comment by MylesBorins** [comment]
There was no intention to rename lts. This was specifically to deal with
the misconceptions around the term stable

**Comment by jasnell** [comment]
This only impacts the Stable branch  naming, not LTS naming.

**Comment by Fishrock123** [comment]
Right, and we all know that this discussion in the past has not just touched on the stable branch. So I'd like to make sure of it.

**Comment by Fishrock123** [comment]
Ok. I definitely think we should really take this past evangelism/marketing. I'm afraid a shift without warning may rub off on downstream customers badly and people may be increasingly hesitant about things if we do it with no prior publicly communicated indicator.

**Comment by stevemao** [comment]
Can we close this since #672 is merged?
