### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by avivkeller** [nodejs/nodejs.org#6749]
In my opinion, the download button on the main page should link to the dedicated download page rather than initiating a direct download of Node.js. This approach aligns with UX best practices, which emphasize the importance of informing users about their actions. When users click a download button, they expect to be provided with details about the file they are downloading.

Additionally, the footnotes that state that the button will directly download are extremely <sup><sub><small>small</small></sub></sup>, and may be difficult for a user to hover over to get more information.

**Comment by ovflowd** [comment]
> This approach aligns with UX best practices, which emphasize the importance of informing users about their actions

This is a contradiction. The button clearly says that it will Download Node.js and it has an icon that illustrates that the button will de facto trigger a download.

This has also been the behaviour for a long period of time, over a decade, and we observed with data collected from session replays over Sentry, that users expect this behaviour (by ruling out rage clicks etc)

Also the home page was designed by a professional designer with solid UX experience, so could you please point out to references on why this is not a good UX practice?

Let's keep personal biases out of this conversation and focus on concrete data.

> Additionally, the footnotes that state that the button will directly download are extremely

By accessibility standards they are the "right size" for footnotes.

**Comment by ovflowd** [comment]
> In my opinion, the download button on the main page should link to the dedicated download 

And with all due respect, Im not going to change the current living behaviour because someone's personal opinion is different from what we as a team agreed, sorry. (Not implying that you are expecting me personally to change it, but just being honest here...) I appreciate you raising the topic, but Im pretty sure everyone here will not agree with your suggestion.

But let's keep the issue open to see what others have to say about the matter :)

**Comment by ovflowd** [comment]
Im not sure if you closed by accident, but if you open an issue at least let more people chime in 😅; other folxs might be interested on this topic and I can still be proven wrong ;)

**Comment by avivkeller** [comment]
> Also the home page was designed by a professional designer with solid UX experience, so could you please point out to references on why this is not a good UX practice?

Yes, they definitely have a better understanding than me, I think this can be closed, sorry for wasting your time. I'll migrate my focus towards the parts of the library that need me most

**Comment by ovflowd** [comment]
> > Also the home page was designed by a professional designer with solid UX experience, so could you please point out to references on why this is not a good UX practice?
> 
> Yes, they definitely have a better understanding than me, I think this can be closed, sorry for wasting your time. I'll migrate my focus towards the parts of the library that need me most

Im not trying to imply that our designer has better knowledge than you. Im just saying that at least in the UX part we are quite sure that best practices got applied, but again, happy to be corrected otherwise or to see tou backing your claims 😅 because Im definitely not an UX professional, although I know one or two things about web design.

This issue doesn't waste my time, it is a valid question. The PR is a waste of time (more for you than for me) and sometimes also not the best place to have such conversations that we are having now, although questionable;

**Comment by avivkeller** [comment]
> Im not trying to imply that our designer has better knowledge than you.

For the record, I'm sure they do

**Comment by Jay-Karia** [comment]
IMO, the download button should say the version which is going to get downloaded with "LTS"

**Comment by Jay-Karia** [comment]
> IMO, the download button should say the version which is going to get downloaded with "LTS"

Maybe this not required.
