### ISSUE TITLE
Make getting packages for Linux easier

### ISSUE THREAD

**Issue by mikemaccana** [nodejs/nodejs.org#676]
There are excellent packages for most of the popular Linux distros, however nodejs.org primarily directs people to fetch .xz archives. There are a couple of drawbacks here:
- Installing archives takes longer - you have to make dirs, set up symlinks to binaries in $PATH, etc.
- Packages can be easily updated along with the rest of the OS - if a new security update comes out, you can use yum / apt to update very quickly.

The RethinkDB website handles Linux much better:

![screen shot 2016-04-09 at 18 48 27](https://cloud.githubusercontent.com/assets/172594/14710988/7be1f390-07cf-11e6-9312-6de8834a2442.png)

Clicking the relevant distro would provide instructions to install the package for that OS. Happy to do the work here, just want to know what people think first.

**Comment by MylesBorins** [comment]
@mikemaccana nice to see you :smile: 

I believe that most of the "Official packages" are fairly out of date, which is part of the reason we don't have them as first class options. That being said, at least for myself, this is something that should be fixed. Are the MariaDB official packages "official" from the distro maintainers, or official as in debs created by the project?

There is a bunch of movement to update things for v6 over the next week, but I imagine once the dust settles would be a good time to attempt an implementation. Perhaps we can discuss requirements here and get a good idea of how to improve the situation for our Linux users.

/cc @nodejs/documentation

**Comment by Knighton910** [comment]
+1 

> Clicking the relevant distro would provide instructions to install the package for that OS. Happy to do the work here, just want to know what people think first.

**Comment by eljefedelrodeodeljefe** [comment]
Was there a problem with official package managers not adopting fast enough or is just no-one tending to a pipeline for every release? I agree that it would be nice to `apt-get install node`.

I see that there are some possibilities to set the repos those package managers to some binaries nodesource is providing though.

**Comment by benjamingr** [comment]
-1 I think the thought is very nice but honestly I've told at least 100 students who usually complain about everything and run various linux distros (mostly ubuntu and debian though) to "install nodejs" and none of them have ever had any issues with installation. I couldn't find any question related to it in StackOverflow and I've never heard or seen anyone complain about it.

I think this is a problem that doesn't really exist (although I'm happy to be convinced otherwise). 

Note we also have https://nodejs.org/en/download/package-manager/

**Comment by mikemaccana** [comment]
@benjamingr How many of those students have subsequently updated when a new node security release has come out? If they're run apt/yum to update, how many would forget the unpackaged node?

**Comment by benjamingr** [comment]
@mikemaccana that's a good question - since they all probably installed it [via a package manager](https://nodejs.org/en/download/package-manager/) I'd _assume_ they all did (just adding a PPA and sudo apt-get) since it is the easiest option and the one most linux users I know look for - but I can't really say. 

I'm definitely :+1: on https://github.com/nodejs/nodejs.org/issues/1297 by the way - and I'm definitely for maintaining packages on the top 10 linux distros better.

I'm also not -1 on this anymore - I think things got a lot better in the last year and a half since I posted my -1 in terms of maintenance stability. 

A PR updating https://nodejs.org/en/download/package-manager/ would be appreciated anyway.

**Comment by aduh95** [comment]
In my experience, students who are asked to install Node.js will just do a `sudo apt install nodejs` in their terminal, and get away with the default node version provided by their distro (which is _most of the time_ Node v4 or Node 0.12 on debian based systems).  
And when a recent version is needed, most of them have no idea where to find the relevent info, and download the current `.tar.xz` which they probably won't ever update.

**Shouldn't the package manager installation be the default?** It is certainly the easiest for the end-user to set up and to maintain up-to-date (except maybe on Windows, because not all of developers there have installed chocolatey yet, but Node.js could encourage it).

**Comment by fhemberger** [comment]
The Node.js project doesn't provide packages for distros themselves, they are created by the respective distro community. So we don't have any influence on how often a package gets updated. Nodesource provides deb (Debian/Ubuntu) and rpm (RHEL/Fedora/CentOS) packages.

So if you want to make sure you get **exactly** the Node.js version you need, you have to download the binaries.

**Comment by mikemaccana** [comment]
What you've said re: no official Node Foundation packages (that's somethign to be addressed), but I trust Nodesource and I think most others are comfortable doing do. Installing an unpackaged version isn't necessary to know what version you're running, and is a great way to end up with a vulnerable version of node installed and never updated.

**Comment by ghost** [comment]
i also came to request a website improvement of "link linux install documentation alongside the download button."

I am now in the process of reinstalling nodejs. I don't know what I did wrong last time but `npm cache clean` died looking for ../lib/utils/unsupported.js .

I'm still not sure where to extract this tar and with what permissions, I'm confident I will be able to find the install docs on my own but I did expect them to be next to the download button.

**Comment by ovflowd** [comment]
@AugustinMauroy, any reason why you closed this? It didn't have updates, but it still seems a relevant topic 🤔. (Usually, closing issues without a comment isn't good, except in cases where it's evident that closing is satisfactory).

We partially addressed this on a UX-fashion on the Website Redesign, but there's still the open question regarding binaries being distributed by Node.js, @Trott I believe it is safe to assume that this specific issue is out of the bounds of the Nodejs.org repository and probably something the build team should handle, no?

**Comment by AugustinMauroy** [comment]
@ovflowd If I do not say to be the desing has been chosen on sigma and nodejs.dev. If the community choose to review the issue, let's do it. But for me the question has been completed

**Comment by ovflowd** [comment]
I have no idea what you just said... And the question isn't completed. Sorry, I'm reopening this.

**Comment by ovflowd** [comment]
Now we can actually close this as nodejs.dev is getting merged into here :)

@mikemaccana once we merged the new pages here, I'll let you know when, please reopen this issue if you still feel like this was not addressed!
