### ISSUE TITLE
Restore/add a redirect for the domain postmorten pgae

### ISSUE THREAD

**Issue by mcollina** [nodejs/nodejs.org#6823]
Where did the domain postmortem was moved to? We should set up a redirect, as other pieces point to it.

Ref: https://github.com/tc39/proposal-async-context/issues/92

**Comment by mcollina** [comment]
cc @ovflowd

**Comment by ovflowd** [comment]
I do not recall now. @bmuenzenmeyer do you remember?

**Comment by bmuenzenmeyer** [comment]
i can go digging - this also don't ring a bell to me - the only post-mortem I was aware of was https://nodejs.org/en/blog/announcements/node-js-march-17-incident

**Comment by bmuenzenmeyer** [comment]
it was deleted as part of https://github.com/nodejs/nodejs.org/pull/4991 - probably just a mistake. i can create a PR to re-add with a redirect

<details><summary>how i found out</summary>
```
git log --diff-filter=D -- locale/en/docs/guides/domain-postmortem.md
```

thanks chat gpt
</details>

**Comment by ovflowd** [comment]
Ah that postmortem? No it was deleted way later. On that PR it got moved to a different folder.

Still trying to remember, but I believe because it was a really old post mortem inside the guides folder and it didn't make sense to be kept as it was not a guide.

We could bring it back as a blog post, as that makes more sense.

**Comment by mcollina** [comment]
The fundamental part is that:

1. the content is restored somewhere
2. a redirect is put in place

**Comment by bmuenzenmeyer** [comment]
working on it now - i found the original inclusion into nodejs/node so we can backdate it
