### ISSUE TITLE
issue in Understanding process.nextTick() document page

### ISSUE THREAD

**Issue by alirezatav** [nodejs/nodejs.org#6920]
### URL:

https://nodejs.org/en/learn/asynchronous-work/understanding-processnexttick

### Browser Name:

Chrome

### Browser Version:

126.0.6478.127

### Operating System:

MacOS

### How to reproduce the issue:

1. I ran the example provided on Mac and Windows. I get different output
2. The document says the function `setImmediate` runs before `setTimeout`
3. but function `setImmediate` always runs after `setTimeout`

**Comment by mikeesto** [comment]
I don't understand the inner workings but I believe it's not deterministic. That's why it is labelled as an "Example output", and there is a caveat at the end: `The exact output may differ from run to run.`

**Comment by ovflowd** [comment]
Exactly as mikeesto mentioned, due to asynchronous behaviour at times the output might be different just due to the nature of these calls being race conditions.

The example itself is bad in a certain way and probably should be replaced as it's common a source of confusion.

Closing this issue for now as there's no bug.
