### ISSUE TITLE
Node download failure

### ISSUE THREAD

**Issue by 645556406** [nodejs/nodejs.org#7031]
### URL:

https://nodejs.org

### Browser Name:

Chrome

### Browser Version:

103.0.5060.134

### Operating System:

mac

### How to reproduce the issue:

nodejs.org has a node failure IP: 104.20.22.46

**Comment by AugustinMauroy** [comment]
Can you give more information about how to reproduce this issue ?

**Comment by 645556406** [comment]
![image](https://github.com/user-attachments/assets/0ad5e7ca-4ee2-487e-9354-f32901ad81ef)
Two curl requests, when the request was resolved to nodejs.org and found that the network failed, but it was normal when the request was resolved to 104.20.23.46. From this, it was determined that there was a problem with nodejs.org's backend service node 104.20.22.46. as shown above

**Comment by bmuenzenmeyer** [comment]
@flakey5 does any of this ring a bell to you from your end, else I am not sure what good next steps are

**Comment by flakey5** [comment]
104.20.23.46 is a Cloudflare ip (https://ipinfo.io/104.20.23.46)

Judging from the logs, I don't think the request was making it to the origin server and this is a problem with connecting to Cloudflare. Cloudflare did some maintenance on a few colos yesterday but I don't think that's what caused it (https://cloudflarestatus.com).

Same ip is being used at the time of me replying and I can get a response with the same command, maybe worth trying the command again now? Otherwise I think it could be an issue with your network

**Comment by 645556406** [comment]
It's true that some countries are not accessible because of the Internet.
Why did I ask this question?
Probably because I was visiting nodejs.org and one of the nodes was available, but the other was not.
Now, it's OK for me to access from other countries.
Before I could and could not access nodes. At present, only VPN can be used to access the corresponding content. This is probably because there are restrictions on the Internet.
