### ISSUE TITLE
Add  `@radix-ui/-` dependabot group

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#7113]
see #7112 
see #7111 
see #7110 
see #7108 
see #7105

**Comment by AugustinMauroy** [comment]
The idea of dependabot groups is to group together packages which have the same version semantics (Sotrybook). Or those that are in the same place (orama, lint).
But in this case, they are under the same scope because they are the same maintainer, but they are in no way linked to each other.
So I think you should leave them independent.

**Comment by bmuenzenmeyer** [comment]
That's a good point. I could see it going either way. They seem to independently version their monorepo, but very clearly release in batches. Checkout https://www.radix-ui.com/primitives/docs/overview/releases. A good example is https://www.radix-ui.com/primitives/docs/overview/releases#june-19-2024 - that would be a good candidate to all go together IMO

**Comment by AugustinMauroy** [comment]
If it publishes them in batches, that just means that there are 8 updates every +-3 months, which is probably not a lot.

**Comment by bmuenzenmeyer** [comment]
im good either way - closing
