### ISSUE TITLE
Explore our crowdin integration options

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/nodejs.org#7121]
The GitHub sync process - visible at https://github.com/nodejs/nodejs.org/pull/7089 is nice but has led to maintainer noise and some manual interventions.

This ticket should explore the use of:

- https://store.crowdin.com/github-action | [Github](https://github.com/crowdin/github-action) with lots of config
- https://store.crowdin.com/in-context (Crowdin In-Context doesn't sync content, it allows to submit translations directly on the side)

From Andriy
> Translations made via In-Context will be saved to your Crowdin project and then synced back to GitHub via connector or GitHub Action

Using both might create the best experience.

demo at https://demo.crowdin.com/

I want to make sure any live integration doesn't impact site performance or security.

**Comment by AugustinMauroy** [comment]
Can we can just to a script that we trigger with a cron job, that create a commit with all transition ?

**Comment by bmuenzenmeyer** [comment]
I dont like a custom approach - I'd rather use vetted, version-controlled tools. The GH Action has a lot of configurability and the support of Crowdin. A custom cron would eventually resemble the action, I suspect.

**Comment by dies** [comment]
Integration via Github Action is definitely a great idea! It's a recommended way to integrate Crowdin with Github. By the way, you can reuse your crowdin.yml. Please let us know if we can help you with the transition.

As for in-context, this technology is really useful for translating product copy, such as UI menu items and button titles, which are super hard to translate without context. Since you're translating MDX, each page itself carries enough context, they're perfectly fine to get good quality translations when translated in Crowdin.

**Comment by ovflowd** [comment]
@bmuenzenmeyer, how are we doing with the GitHub Actions implementation? Did you get any time to start a draft here?

**Comment by bmuenzenmeyer** [comment]
I started it and then got distracted by collab summit / travel and not having 1password access at the time. 

I can try to land a draft soon.
