### ISSUE TITLE
UI/UX: when i hover over the dropdown the list item that i am hovering over gets disappeared 

### ISSUE THREAD

**Issue by Abhi-Bohora** [nodejs/nodejs.org#7185]
### What steps will reproduce the bug?

go to the `https://nodejs.org/en/download/package-manager` and click on dropdown. The item you are currently hovering over gets disappeared.

### How often does it reproduce? Is there a required condition?

This is just a simple UI bug

### What is the expected behavior? Why is that the expected behavior?

I should see the name of the item which i am hovering over instead of black sort of thing.

### What do you see instead?

![node](https://github.com/user-attachments/assets/bcab3e59-deb5-4082-802b-5adc13a7e885)

**Comment by AugustinMauroy** [comment]
Confirm ! IDK when we introduce that

**Comment by AugustinMauroy** [comment]
[Figma link](https://www.figma.com/design/pu1vZPqNIM7BePd6W8APA5/Node.js?node-id=719-8395) of the component.
It's affecting the [Select](https://github.com/nodejs/nodejs.org/tree/270a37a89f7bf033598b87ae07f92ff8080a5ab5/apps/site/components/Common/Select) component

**Comment by canerakdas** [comment]
@AugustinMauroy  In [this PR](https://github.com/nodejs/nodejs.org/pull/7179) I updated the class strategy with the selector strategy, this PR seems to have caused this issue

AFAIK It looked right because of a feature not working properly in the old strategy. Because the style given to the attribute is more specific than the style given to the element itself 🤔 

@Abhi-Bohora  thank you for informing
