### ISSUE TITLE
Add Vetted Courses

### ISSUE THREAD

**Issue by mcollina** [nodejs/nodejs.org#7201]
We have recently starded the @nodejs/ambassadors program, and most of them are educators. I propose we add a few links to their courses if they would be willing to have a @nodejs/tsc member (or delegate) review their material.

We should also link to the courses maintained by the Linux Foundation:
- https://training.linuxfoundation.org/training/introduction-to-nodejs-lfw111/
- https://training.linuxfoundation.org/training/nodejs-application-development-lfw211/

The link should include the name of the ambassador and the year this was last edited.

**Comment by AugustinMauroy** [comment]
+1 for "trusted" ressources like resources from our contributor. but big -1 for paid ressources.
I know creating content ask a lot of time and energy. But IMHO we shouldn't redirect to paid ressource.

**Comment by RafaelGSS** [comment]
My perspective on this from the discussion in the last TSC meeting is that including paid courses would make things unfair. Although Node.js TSC could review the content before allowing the resource to be on the list, this is not mandatory, and I doubt someone would have time to review all courses *for free* and provide feedback *for free* to the educators.

One of the points raised in the meeting is that there are a bunch of courses out there with outdated information (or plenty wrong in some cases) and providing a "trusted" list would move Node.js developers in the right direction... My concern here is that is very hard to make sure we are pointing them in the right direction, as I said, it would be hard to review content and make sure they are up-to-date.

**Comment by mhdawson** [comment]
I see the concern that @RafaelGSS raises, but I also see value in narrowing down choices to ones that are more likely to be up to date and aligned with current state of the art. 

The project cannot validate all content (or really any substantial part of the content we'd like to have) and the ambassador program is an attempt to work more closely with some educators who have the best interests in mind, starting with a level of trust that they won't be sharing or recommending content that is out of date, invalid etc. 

If it turns out that ambassadors don't follow that spirit, then we'll find out over time and they will no longer be ambassadors. The model is to find people we trust to do the right thing, versus trying to validate the content because we won't/don't have volunteers to do that. Instead the program includes the opportunity for project members to review if they have time, but does not block on that trusting that ambassadors will do the right thing. Similar to how we give collaborators a level of access that lets them efficiently move things forward and trust them to use that access appropriately.

I do understand the concern that it might not work out, but giving trust to collaborators has generally worked in terms out outcomes and I think it is worth trying versus not being able to recommend/showcase any content at all.

**Comment by RafaelGSS** [comment]
Wouldn't you think that promoting a course from an author will make a unfair advantage over the ones that aren't in the ambassador's program? I might be missing the end goal but I feel this market-wise unfair

**Comment by mcollina** [comment]
Yes it is, and that's a good thing. We would be promoting people that are willing to _help_ the project and avoid promoting bad patterns. In turn, more educator will follow their lead wanting to become ambassadors and help teach developers how to use Node correctly. "Old content" will fade away, or it will get updated to follow these guidelines.

**Comment by ovflowd** [comment]
Should we announce this somewhere?
