### ISSUE TITLE
New Node.js Desktop Background?

### ISSUE THREAD

**Issue by bnb** [nodejs/nodejs.org#768]
- **URL**: https://nodejs.org/en/about/resources/

The Desktop Background is out of date - old logo. It should definitely be kept somewhere for nostalgia purposes, but we should either commission or request a new Desktop Background. 

**As a member of the Evangelism WG:**
Would the Website WG be opposed if we held a contest or some other form of community event advertised on our blog and over our social media accounts to get desktop backgrounds and mobile backgrounds with the new logo created by the community? My idea would be to publish ones of high quality to the website (there will obviously be poor quality ones). 

//cc @nodejs/evangelism

**Comment by fhemberger** [comment]
@bnb Google Analytics hits for `/static/images/logos/nodejs-*` since you opened this issue (~19 months):

![bildschirmfoto 2017-12-19 um 10 29 45](https://user-images.githubusercontent.com/153481/34150151-cd01836a-e4a7-11e7-9a0e-cd2c1cd0a581.png)

I'd say we can simply remove the desktop wallpaper. What do you think?
