### ISSUE TITLE
Newer npm versions in https://nodejs.org/dist

### ISSUE THREAD

**Issue by shobhitg** [nodejs/nodejs.org#773]
Hi,

Please refer this issue: https://github.com/npm/npm/issues/12930

I am trying to use frontend-maven-plugin for installing nodejs.

But unfortunately it seems that NodeJS is sooo much fragmented from NPM itself in terms of responsibility.

frontend-maven-plugin downloads nodejs from this place: https://nodejs.org/dist
For nodejs, we have the latest versions (v6.2.0).
But it seems that newer npm version binaries aren't making into https://nodejs.org/dist

I am really wishing to make this work for my team.

Please advise, what can I do to have npm 3 versions make it into https://nodejs.org/dist?

**Comment by MylesBorins** [comment]
@shobhitg we ship node.js with a version of npm that has been sent to us as stable by the npm team and tested to work with that specific version of node. We have not been publishing specific versions of npm without node to the download site, but have kept old versions on there to not break things.

I am not under the impression that we are going to change this.

Node.js comes packed with a working version of npm, and it should be possible for `frontend-maven-plugin` to update their package to utilize this instead of a legacy path not used in any of our released lines (all versions of node that we are currently releasing have npm v2 or higher)

I'm going to close this issue as the website itself is not responsible for this, but please feel free to open another issue on http://github.com/nodejs/build to track this

We appreciate your patience while getting bounced around. Feel free to keep a conversation going in here even though the issue is closed. 

would you be willing to share what you are using the maven plugin for? It seems to imply that it should only be used for development, and I'm not convinced it is the best workflow

/cc @nodejs/build

**Comment by shobhitg** [comment]
Yes, it is not the best workflow. I agree.
But we live in a Java dominated world. And maven is to Java what npm is to Node.

Therefore in large products that are dominated by Java, the NodeJS lovers need to squeeze themselves in somehow.
The 1st important step for that is to be part of the build system.
Till now things were cool, frontend-maven-plugin would handle it. But as npm 3 is becoming a norm, we have to force ourselves to use npm 3. But facing issues, as discussed in these threads.

Actually, I am just realizing that since the latest v6.2.0 contains npm 3 within it, maybe its already a solvable issue. I need to test that. Will update later.

**Comment by MylesBorins** [comment]
@shobhitg I think it worked by accident to be honest. If it were setup to be using the latest npm available in the download page you would have been always getting npm v1 which is not only less reliable, but also ships with some security vulns...

0.10 / 0.12 / 4 all ship with npm v2
5 / 6 ships with npm v3

I think opening an issue on build about fitting into the java ecosystem is a great start... the last thing we need is a bunch of users unknowingly using vulnerable code
