### ISSUE TITLE
Why is the displayed "current version" so out of date?

### ISSUE THREAD

**Issue by pgorbas** [nodejs/nodejs.org#782]
- **URL**: https://nodejs.org/en/download/
- **Browser version**: Chrome Version 51.0.2704.84 m
- **Operating system**: Windows 10

I thought I needed to update my NPM to get it to install angular2/rc-1.

The Download page states the most current version is "Current version: v4.4.5 (includes npm 2.15.5)",
but when I tried to install it I could not because I already had a more current version installed.

Doing a "Node-v" revealed I hade Node v5.10.1, which is what comes with VS2015.

How can my year old VS2015 node be on version 5.10.1 while you claim the most recent version is only 4.4.5

**Comment by ghost** [comment]
hi! basically there's two release lines. we have _LTS_, which is currently at 4.4.5. this is kept at an earlier version in order to make it more stable and reliable. lots of enterprise companies use the LTS releases because of that.

then we also have _current_ (https://nodejs.org/en/download/current/). this is the brand new, fresh-off-the-press release that has the latest features. this one's at 6.2.1. so, you have an older _current_ release installed (5.10.1).
