### ISSUE TITLE
release-post script breaks if there is a line after a header link

### ISSUE THREAD

**Issue by evanlucas** [nodejs/nodejs.org#837]
If there is a line after the `<a id="6.3.1"></a>` header link in node changelogs, the release-post script breaks

**Comment by lpinca** [comment]
The problem is in these two regex [1](https://github.com/nodejs/nodejs.org/blob/bd2149b90b8f04b994efe664758b04e071a9780f/scripts/release-post.js#L103), [2](https://github.com/nodejs/nodejs.org/blob/bd2149b90b8f04b994efe664758b04e071a9780f/scripts/release-post.js#L150). The second one does not match as there is a leading `\n`.
I think the beast approach to fix this is to trim the matched [section](https://github.com/nodejs/nodejs.org/blob/bd2149b90b8f04b994efe664758b04e071a9780f/scripts/release-post.js#L106).
